/**
* @file:         CanListDef.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.23, 14:45:06
* @brief:        
* @attention:    
**/

#pragma once

#include <stdint.h>


/*
* 路由结构体
*/
typedef struct Msgdef_t
{
	uint8_t 源地址 : 1;
	uint32_t id;
	uint8_t dlc;
	uint8_t 目标地址 : 1;
	uint32_t time;
	uint8_t E1 : 1;
	uint8_t E2 : 1;
} Msgdef_t;


/*
* 路由列表
*/
extern const Msgdef_t ListMsg[];


/*
* 路由列表的长度
*/
extern const uint16_t ListMsgLenght;


/******** END OF FILE ********/
