/**
* @file:         CanListDef.c
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.23, 14:45:06
* @brief:        
* @attention:    
**/

#include "CanListDef.h"
#include "GW_global.h"


const Msgdef_t ListMsg[] = {

	{ BCAN, 0x31, 8, CCAN, 0, 1, 1, },
	{ BCAN, 0x40, 8, CCAN, 0, 1, 1, },
	{ BCAN, 0x23A, 8, CCAN, 40, 1, 1, },
	{ BCAN, 0x280, 8, CCAN, 0, 0, 1, },
	{ BCAN, 0x321, 8, CCAN, 100, 1, 1, },
	{ BCAN, 0x322, 8, CCAN, 100, 1, 1, },
	{ BCAN, 0x33C, 8, CCAN, 100, 1, 1, },
	{ BCAN, 0x341, 8, CCAN, 100, 1, 1, },
	{ BCAN, 0x366, 8, CCAN, 500, 0, 1, },
	{ BCAN, 0x371, 8, CCAN, 100, 0, 1, },
	{ BCAN, 0x37C, 8, CCAN, 100, 1, 1, },
	{ BCAN, 0x3B0, 8, CCAN, 100, 0, 1, },
	{ BCAN, 0x413, 8, CCAN, 500, 0, 1, },
	{ BCAN, 0x4DA, 8, CCAN, 1000, 0, 1, },
	{ BCAN, 0x4FD, 8, CCAN, 500, 0, 1, },

	{ CCAN, 0x1F, 8, BCAN, 0, 1, 1, },
	{ CCAN, 0x41, 8, BCAN, 0, 1, 1, },
	{ CCAN, 0xA0, 8, BCAN, 10, 1, 1, },
	{ CCAN, 0xA5, 8, BCAN, 10, 1, 1, },
	{ CCAN, 0xF6, 8, BCAN, 20, 1, 1, },
	{ CCAN, 0x0FE, 8, BCAN, 20, 1, 1, },
	{ CCAN, 0x121, 8, BCAN, 20, 1, 1, },
	{ CCAN, 0x123, 8, BCAN, 20, 1, 1, },
	{ CCAN, 0x30C, 8, BCAN, 100, 1, 1, },
	{ CCAN, 0x31A, 8, BCAN, 100, 1, 1, },
	{ CCAN, 0x355, 8, BCAN, 100, 1, 1, },
	{ CCAN, 0x3DB, 8, BCAN, 500, 1, 1, },
	{ CCAN, 0x431, 8, BCAN, 1000, 1, 1, },
	{ CCAN, 0x4AF, 8, BCAN, 100, 1, 1, },

};


const uint16_t ListMsgLenght = sizeof(ListMsg) / sizeof(ListMsg[0]);


/******** END OF FILE ********/
