/**
* @file:         ACAN_config.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.08, 11:17:43
* @brief:        
* @attention:    
**/

#pragma once

/*
* 该宏定义是信号报文周期相关功能的系数。与信号报文的发送，信号报文的超时处理相关。
* 该值代表ACAN_Cyc_Transmit(void)函数每次执行的间隔（调用周期），单位为毫秒（ms）。
* 总累加时间 = 当前累加时间 + 周期系数;
* 当总累加时间超过报文周期，会执行ACAN_MsgCycAOP.h中的以CycleOverFunc以前缀的方法，通常在这里执行发送信号报文。
* 当总累加时间大于超时时间，会执行ACAN_MsgCycAOP.h中的以TimeoutFunc为前缀的方法，通常在这里执行超时处理。
*/
#define CYCLE_FACTOR (10U)


/******** END OF FILE ********/
