/**
* @file:         ACAN_MsgCycAOP.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.08, 11:17:43
* @brief:        
* @attention:    
**/

#pragma once

void ACAN_TimeoutFunc_IC_TCO1(void);
void ACAN_TimingFunc_IC_TCO1(void);
void ACAN_CycleOverFunc_IC_TCO1(void);

void ACAN_TimeoutFunc_New_Message_5(void);
void ACAN_TimingFunc_New_Message_5(void);
void ACAN_CycleOverFunc_New_Message_5(void);

void ACAN_TimeoutFunc_EMS_CCVS(void);
void ACAN_TimingFunc_EMS_CCVS(void);
void ACAN_CycleOverFunc_EMS_CCVS(void);

void ACAN_TimeoutFunc_IC_CCVS1(void);
void ACAN_TimingFunc_IC_CCVS1(void);
void ACAN_CycleOverFunc_IC_CCVS1(void);

void ACAN_TimeoutFunc_BCM_CCVS(void);
void ACAN_TimingFunc_BCM_CCVS(void);
void ACAN_CycleOverFunc_BCM_CCVS(void);



/******** END OF FILE ********/
