/**
* @file:         ACAN_MsgParseAOP.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.08, 11:17:43
* @brief:        
* @attention:    
**/

#pragma once

void BeforeParse_ACAN_IC_TCO1(void);
void AfterParse_ACAN_IC_TCO1(void);

void BeforeParse_ACAN_New_Message_5(void);
void AfterParse_ACAN_New_Message_5(void);

void BeforeParse_ACAN_EMS_CCVS(void);
void AfterParse_ACAN_EMS_CCVS(void);

void BeforeParse_ACAN_IC_CCVS1(void);
void AfterParse_ACAN_IC_CCVS1(void);

void BeforeParse_ACAN_BCM_CCVS(void);
void AfterParse_ACAN_BCM_CCVS(void);



/******** END OF FILE ********/
