/**
* @file:         ACAN_CycleAct.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.08, 11:17:43
* @brief:        
* @attention:    
**/

#pragma once

#include "ACAN_monitorutil.h"


/*
* 该函数用来放需要进行周期动作的信号报文。
*/
void CycleActFunc(void);

/*
* 该函数与三个函数关联。
*/
void RegularlyCallFunc(ACAN_FrameMonitor_t* monitor);
 

/******** END OF FILE ********/
