/**
* @file:         abc_monitorutil.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#pragma once

#include <stdbool.h>
#include <stdint.h>


typedef struct
{
	// 报文周期，单位毫秒（ms）。
	const uint32_t cycle;

	// 报文周期计时，单位毫秒（ms）。
	uint32_t cycle_cnt;

	// 周期循环执行函数。
	void(*CycleOverFunc)(void);

	// 当最后一帧报文被接收的时候保存时值。
	uint32_t last_cycle;

	// 报文的最大超时时间，单位毫秒（ms）。
	const uint32_t timeout_cycle;

	// 报文超时计数，单位毫秒（ms）。
	uint32_t timeout_cnt;

	// 超时执行函数。
	void(*TimeoutFunc)(void);

	// 记录最近的一帧报文的数据。

	// 记录接收到的报文帧数。
	uint32_t frame_cnt;

	// 该位表示收到CAN帧的实际长度与CAN矩阵定义的长度不符。
	bool dlc_error;

	// 调用周期定时执行函数
	void(*TimingFunc)(void);
} abc_FrameMonitor_t;


/*
* 执行解包时将调用此函数。
* 返回值将保存在@last_cycle变量中。表示某条报文最后一次接收到的时间。
*/
uint32_t abc_GetSystemTick(void);


/*
* 重置监视器计时。
* 重置以下变量:
* @cycle_cnt、@timeout_cnt
*/
void abc_ResetMonitor(abc_FrameMonitor_t* monitor);

/******** END OF FILE ********/
