/**
* @file:         abc_CycleAct.c
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#include "abc_CycleAct.h"
#include "abc_binutil.h"
#include "abc_config.h"


void CycleActFunc(void)
{

}

void RegularlyCallFunc(abc_FrameMonitor_t* monitor)
{
	monitor->timeout_cnt += CYCLE_FACTOR;
	monitor->cycle_cnt += CYCLE_FACTOR;

	if(monitor->timeout_cnt >= monitor->timeout_cycle){
		monitor->timeout_cnt = monitor->timeout_cycle;
		monitor->TimeoutFunc();
	}

	monitor->TimingFunc();

	if(monitor->cycle_cnt >= monitor->cycle){
		monitor->cycle_cnt = 0;
		monitor->CycleOverFunc();
	}
}




/******** END OF FILE ********/
