/**
* @file:         abc_CycleAct.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#pragma once

#include "abc_monitorutil.h"


/*
* 该函数用来放需要进行周期动作的信号报文。
* 需要自行添加。
*/
void CycleActFunc(void);


/*
* 该函数用来执行具体的周期动作。
*/
void RegularlyCallFunc(abc_FrameMonitor_t* monitor);


/******** END OF FILE ********/
