/**
* @file:         abc_MsgCycAOP.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#pragma once

void abc_TimeoutFunc_IC_TCO1(void);
void abc_TimingFunc_IC_TCO1(void);
void abc_CycleOverFunc_IC_TCO1(void);

void abc_TimeoutFunc_New_Message_5(void);
void abc_TimingFunc_New_Message_5(void);
void abc_CycleOverFunc_New_Message_5(void);

void abc_TimeoutFunc_EMS_CCVS(void);
void abc_TimingFunc_EMS_CCVS(void);
void abc_CycleOverFunc_EMS_CCVS(void);

void abc_TimeoutFunc_IC_CCVS1(void);
void abc_TimingFunc_IC_CCVS1(void);
void abc_CycleOverFunc_IC_CCVS1(void);

void abc_TimeoutFunc_BCM_CCVS(void);
void abc_TimingFunc_BCM_CCVS(void);
void abc_CycleOverFunc_BCM_CCVS(void);



/******** END OF FILE ********/
