/**
* @file:         abc_monitorutil.c
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#include "abc_monitorutil.h"


uint32_t abc_GetSystemTick(void)
{
	return 0;
}


void abc_ResetMonitor(abc_FrameMonitor_t* monitor)
{
	monitor->cycle_cnt = 0;
	monitor->timeout_cnt = 0;
}




/******** END OF FILE ********/
