/**
* @file:         abc_MsgParseAOP.h
* @author:       96400
* @note:         The code is automatically generated by GatewayTool
* @version:      V1.0.0
* @date:         2023.02.09, 14:29:32
* @brief:        
* @attention:    
**/

#pragma once

void BeforeParse_abc_IC_TCO1(void);
void AfterParse_abc_IC_TCO1(void);

void BeforeParse_abc_New_Message_5(void);
void AfterParse_abc_New_Message_5(void);

void BeforeParse_abc_EMS_CCVS(void);
void AfterParse_abc_EMS_CCVS(void);

void BeforeParse_abc_IC_CCVS1(void);
void AfterParse_abc_IC_CCVS1(void);

void BeforeParse_abc_BCM_CCVS(void);
void AfterParse_abc_BCM_CCVS(void);



/******** END OF FILE ********/
