/**
* @file         BCAN_MsgCycAOP.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

extern void BCAN_TimeoutFunc_FCTB_IC_ESC2(void);
extern void BCAN_TimingFuncFCTB_IC_ESC2(void);
extern void BCAN_CycleOverFuncFCTB_IC_ESC2(void);

extern void BCAN_TimeoutFunc_FCTB_IC_SAS_info(void);
extern void BCAN_TimingFuncFCTB_IC_SAS_info(void);
extern void BCAN_CycleOverFuncFCTB_IC_SAS_info(void);

extern void BCAN_TimeoutFunc_FCTB_IC_ESC3(void);
extern void BCAN_TimingFuncFCTB_IC_ESC3(void);
extern void BCAN_CycleOverFuncFCTB_IC_ESC3(void);

extern void BCAN_TimeoutFunc_FCTB_IC_ESC6(void);
extern void BCAN_TimingFuncFCTB_IC_ESC6(void);
extern void BCAN_CycleOverFuncFCTB_IC_ESC6(void);

extern void BCAN_TimeoutFunc_FBTC_IBCM2(void);
extern void BCAN_TimingFuncFBTC_IBCM2(void);
extern void BCAN_CycleOverFuncFBTC_IBCM2(void);

extern void BCAN_TimeoutFunc_FCTB_GW_ACU_Crash(void);
extern void BCAN_TimingFuncFCTB_GW_ACU_Crash(void);
extern void BCAN_CycleOverFuncFCTB_GW_ACU_Crash(void);

extern void BCAN_TimeoutFunc_FCTB_IC_ESC_EPB1(void);
extern void BCAN_TimingFuncFCTB_IC_ESC_EPB1(void);
extern void BCAN_CycleOverFuncFCTB_IC_ESC_EPB1(void);

extern void BCAN_TimeoutFunc_FBTC_AC1(void);
extern void BCAN_TimingFuncFBTC_AC1(void);
extern void BCAN_CycleOverFuncFBTC_AC1(void);

extern void BCAN_TimeoutFunc_FBTC_IBCM3(void);
extern void BCAN_TimingFuncFBTC_IBCM3(void);
extern void BCAN_CycleOverFuncFBTC_IBCM3(void);

extern void BCAN_TimeoutFunc_FBTC_IBCM6(void);
extern void BCAN_TimingFuncFBTC_IBCM6(void);
extern void BCAN_CycleOverFuncFBTC_IBCM6(void);

extern void BCAN_TimeoutFunc_FCTB_CGW_VCU5(void);
extern void BCAN_TimingFuncFCTB_CGW_VCU5(void);
extern void BCAN_CycleOverFuncFCTB_CGW_VCU5(void);

extern void BCAN_TimeoutFunc_FBTC_MP5_2(void);
extern void BCAN_TimingFuncFBTC_MP5_2(void);
extern void BCAN_CycleOverFuncFBTC_MP5_2(void);

extern void BCAN_TimeoutFunc_FBTC_AC_Front2(void);
extern void BCAN_TimingFuncFBTC_AC_Front2(void);
extern void BCAN_CycleOverFuncFBTC_AC_Front2(void);

extern void BCAN_TimeoutFunc_FCTB_CBS2(void);
extern void BCAN_TimingFuncFCTB_CBS2(void);
extern void BCAN_CycleOverFuncFCTB_CBS2(void);

extern void BCAN_TimeoutFunc_FBTC_MP5_6(void);
extern void BCAN_TimingFuncFBTC_MP5_6(void);
extern void BCAN_CycleOverFuncFBTC_MP5_6(void);

extern void BCAN_TimeoutFunc_FCTB_GW_ESC7(void);
extern void BCAN_TimingFuncFCTB_GW_ESC7(void);
extern void BCAN_CycleOverFuncFCTB_GW_ESC7(void);

extern void BCAN_TimeoutFunc_FBTC_MP5_TBOX_Time(void);
extern void BCAN_TimingFuncFBTC_MP5_TBOX_Time(void);
extern void BCAN_CycleOverFuncFBTC_MP5_TBOX_Time(void);

extern void BCAN_TimeoutFunc_FBTC_MP5_Mode(void);
extern void BCAN_TimingFuncFBTC_MP5_Mode(void);
extern void BCAN_CycleOverFuncFBTC_MP5_Mode(void);



/******** END OF FILE ********/
