/**
* @file         BCAN_config.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#define UNPACK_AFTER_ACT#define CYCLE_FACTOR 1


/******** END OF FILE ********/
