/**
* @file         BCAN_definition.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#include <stdint.h>
#include "BCAN_config.h"
#include "BCAN_monitor.h"

/*
def @FBTC_MP5_Mode CAN Message (1277 0x4fd)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_MP5_Mode_IDE (0U)
#define FBTC_MP5_Mode_DLC (8U)
#define FBTC_MP5_Mode_CANID (0x4fd)
#define FBTC_MP5_Mode_CYC (500U) // ms

typedef struct
{
	uint8_t MP5_VehiclePowerSwitch : 2;          //      Bits= 2 Factor= 1

	uint8_t MP5_DriveModeSET : 4;                //      Bits= 4 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_MP5_Mode_t;

uint32_t Unpack_BCAN_FBTC_MP5_Mode(BCAN_FBTC_MP5_Mode_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_MP5_Mode(BCAN_FBTC_MP5_Mode_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_CBS2 CAN Message (1023 0x3ff)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_CBS2_IDE (0U)
#define FCTB_CBS2_DLC (8U)
#define FCTB_CBS2_CANID (0x3ff)
#define FCTB_CBS2_CYC (100U) // ms

typedef struct
{
	uint8_t CWB_DimmingSwitch : 2;               //      Bits= 2 Factor= 1

	uint8_t CWB_PreWashingSwitch : 2;            //      Bits= 2 Factor= 1

	uint8_t CWB_TurnSwitch : 3;                  //      Bits= 3 Factor= 1

	uint8_t CWB_FrontWiperSwitch : 3;            //      Bits= 3 Factor= 1

	uint8_t CWB_FrontWiperAdjustment : 3;        //      Bits= 3 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_CBS2_t;

uint32_t Unpack_BCAN_FCTB_CBS2(BCAN_FCTB_CBS2_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_CBS2(BCAN_FCTB_CBS2_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_IC_ESC_EPB1 CAN Message (794 0x31a)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_IC_ESC_EPB1_IDE (0U)
#define FCTB_IC_ESC_EPB1_DLC (8U)
#define FCTB_IC_ESC_EPB1_CANID (0x31a)
#define FCTB_IC_ESC_EPB1_CYC (100U) // ms

typedef struct
{
	uint8_t ESC_EPBDisplayMessageReq : 3;        //      Bits= 3 Factor= 1

	uint8_t ESC_EPBCruiseControlCancel : 1;      //      Bits= 1 Factor= 1

	uint8_t ESC_EPBWarningIndicationReq : 2;     //      Bits= 2 Factor= 1

	uint8_t ESC_EPBAudibleWarnningRequest : 2;   //      Bits= 2 Factor= 1

	uint8_t ESC_EPBSystemStIndicationReq : 2;    //      Bits= 2 Factor= 1

	uint8_t ESC_EPBSwitchStatics : 2;            //      Bits= 2 Factor= 1

	uint8_t ESC_EPBSwitchStaticsValidity : 1;    //      Bits= 1 Factor= 1

	uint8_t ESC_EPBStatus : 3;                   //      Bits= 3 Factor= 1

	uint16_t ESC_CurrentOnRightRearCaliper : 10; //      Bits= 10 Factor= 1

	uint16_t ESC_CurrentOnLeftRearCaliper : 10;  //      Bits= 10 Factor= 1

	uint8_t ESC_EPBErrorStatus : 2;              //      Bits= 2 Factor= 1

	uint8_t ESC_PbcActuatorStateRight : 3;       //      Bits= 3 Factor= 1

	uint8_t ESC_PbcActuatorStateLeft : 3;        //      Bits= 3 Factor= 1

	uint8_t ESC_RollingCount_EPB : 4;            //      Bits= 4 Factor= 1

	uint8_t ESC_CheckSum_EPB : 8;                //      Bits= 8 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_IC_ESC_EPB1_t;

uint32_t Unpack_BCAN_FCTB_IC_ESC_EPB1(BCAN_FCTB_IC_ESC_EPB1_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_IC_ESC_EPB1(BCAN_FCTB_IC_ESC_EPB1_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_IC_ESC3 CAN Message (289 0x121)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_IC_ESC3_IDE (0U)
#define FCTB_IC_ESC3_DLC (8U)
#define FCTB_IC_ESC3_CANID (0x121)
#define FCTB_IC_ESC3_CYC (20U) // ms

typedef struct
{
	uint8_t ESC_ReqDecreaseTorqueFlag : 1;       //      Bits= 1 Factor= 1

	uint8_t ESC_ReqIncreaseTorqueFlag : 1;       //      Bits= 1 Factor= 1

	uint8_t ESC_TCSCtlActive : 2;                //      Bits= 2 Factor= 1

	uint8_t ESC_ESCAlarmSig : 1;                 //      Bits= 1 Factor= 1

	uint8_t ESC_ESCWorkStatus : 1;               //      Bits= 1 Factor= 1

	uint8_t ESC_keepingGear : 1;                 //      Bits= 1 Factor= 1

	uint8_t ESC_ESCOFF : 1;                      //      Bits= 1 Factor= 1

	uint16_t ESC_ReqIncreaseTorque : 12;         //      Bits= 12 Factor= 1

	uint16_t ESC_ReqDecreaseTorque : 12;         //      Bits= 12 Factor= 1

	uint8_t ESC_epbRequest : 2;                  //      Bits= 2 Factor= 1

	uint8_t ESC_wheelDirectionRLValid : 1;       //      Bits= 1 Factor= 1

	uint8_t ESC_wheelDirectionRRValid : 1;       //      Bits= 1 Factor= 1

	uint8_t ESC_FRWDirection : 2;                //      Bits= 2 Factor= 1

	uint8_t ESC_FLWDirection : 2;                //      Bits= 2 Factor= 1

	uint8_t ESC_RRWDirection : 2;                //      Bits= 2 Factor= 1

	uint8_t ESC_RLWDirection : 2;                //      Bits= 2 Factor= 1

	uint8_t ESC_ESCValidity : 1;                 //      Bits= 1 Factor= 1

	uint8_t ESC_vehicleStandstillValid : 1;      //      Bits= 1 Factor= 1

	uint8_t ESC_TCSErrorStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t ESC_VehicleStandstill : 2;           //      Bits= 2 Factor= 1

	uint8_t GW_ESC_RollingCount_ESC3 : 4;        //      Bits= 4 Factor= 1

	uint8_t GW_ESC_CheckSum_ESC3 : 8;            //      Bits= 8 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_IC_ESC3_t;

uint32_t Unpack_BCAN_FCTB_IC_ESC3(BCAN_FCTB_IC_ESC3_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_IC_ESC3(BCAN_FCTB_IC_ESC3_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_IC_ESC6 CAN Message (291 0x123)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_IC_ESC6_IDE (0U)
#define FCTB_IC_ESC6_DLC (8U)
#define FCTB_IC_ESC6_CANID (0x123)
#define FCTB_IC_ESC6_CYC (20U) // ms

typedef struct
{
	uint8_t ESC_DynamicSlopeAccuracy : 2;        //      Bits= 2 Factor= 1

	uint8_t ESC_AVHFunctionSwitch : 1;           //      Bits= 1 Factor= 1

	uint8_t ESC_AVHAvailable : 1;                //      Bits= 1 Factor= 1

	uint8_t ESC_AVH_Status : 1;                  //      Bits= 1 Factor= 1

	uint8_t ESC_AVH_DisplayMessageReq : 1;       //      Bits= 1 Factor= 1

	uint8_t ESC_BLRequest : 1;                   //      Bits= 1 Factor= 1

	uint8_t ESC_EmergencyBrakeLightReq : 1;      //      Bits= 1 Factor= 1

	uint8_t ESC_BrakingEffort : 1;               //      Bits= 1 Factor= 1

	uint8_t ESC_MSRinRegulation : 1;             //      Bits= 1 Factor= 1

	uint8_t ESC_BrakeReleasedFailsafe : 1;       //      Bits= 1 Factor= 1

	uint16_t ESC_UnfilteredYawRate : 12;         //      Bits= 12 Factor= 1

	uint8_t ESC_VehDrivingDirection : 2;         //      Bits= 2 Factor= 1

	uint8_t ESC_DynamicSlope : 6;                //      Bits= 6 Factor= 1

	uint8_t ESC_VehicleHoldStatus : 2;           //      Bits= 2 Factor= 1

	uint8_t ESC_cdpAvailable : 1;                //      Bits= 1 Factor= 1

	uint8_t ESC_cdpActive : 1;                   //      Bits= 1 Factor= 1

	uint8_t ESC_HBAStatus : 2;                   //      Bits= 2 Factor= 1

	uint8_t ESC_RollingCount_ESC6 : 4;           //      Bits= 4 Factor= 1

	uint8_t ESC_CheckSum_ESC6 : 8;               //      Bits= 8 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_IC_ESC6_t;

uint32_t Unpack_BCAN_FCTB_IC_ESC6(BCAN_FCTB_IC_ESC6_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_IC_ESC6(BCAN_FCTB_IC_ESC6_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_CGW_VCU5 CAN Message (853 0x355)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_CGW_VCU5_IDE (0U)
#define FCTB_CGW_VCU5_DLC (8U)
#define FCTB_CGW_VCU5_CANID (0x355)
#define FCTB_CGW_VCU5_CYC (100U) // ms

typedef struct
{
	uint8_t VCU_DrivingPermit : 1;               //      Bits= 1 Factor= 1

	uint8_t PDCU_ShiftLvlPosn : 3;               //      Bits= 3 Factor= 1

	uint8_t PDCU_SysFaultWarn : 1;               //      Bits= 1 Factor= 1

	uint8_t PDCU_PrfmncLimitedWarn : 1;          //      Bits= 1 Factor= 1

	uint8_t VCU_PumpInvalidWarning : 2;          //      Bits= 2 Factor= 1

	uint16_t PDCU_CruisingRange : 10;            //      Bits= 10 Factor= 1

	uint8_t PDCU_ParkLockSt : 2;                 //      Bits= 2 Factor= 1

	uint8_t PDCU_ActualRegenLvl : 3;             //      Bits= 3 Factor= 1

	uint8_t PDCU_DCDCworkSt : 2;                 //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_CGW_VCU5_t;

uint32_t Unpack_BCAN_FCTB_CGW_VCU5(BCAN_FCTB_CGW_VCU5_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_CGW_VCU5(BCAN_FCTB_CGW_VCU5_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_AC_Front2 CAN Message (892 0x37c)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_AC_Front2_IDE (0U)
#define FBTC_AC_Front2_DLC (8U)
#define FBTC_AC_Front2_CANID (0x37c)
#define FBTC_AC_Front2_CYC (100U) // ms

typedef struct
{
	uint8_t AC_InCarTemp : 8;                    //      Bits= 8 Factor= 1

	uint8_t AC_FrontEvapTempTarget : 8;          //      Bits= 8 Factor= 1

	uint16_t AC_FrontHeaterInletTempSet : 16;    //      Bits= 16 Factor= 1

	uint8_t AC_FrontACStartReq : 2;              //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_AC_Front2_t;

uint32_t Unpack_BCAN_FBTC_AC_Front2(BCAN_FBTC_AC_Front2_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_AC_Front2(BCAN_FBTC_AC_Front2_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_MP5_6 CAN Message (1043 0x413)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_MP5_6_IDE (0U)
#define FBTC_MP5_6_DLC (8U)
#define FBTC_MP5_6_CANID (0x413)
#define FBTC_MP5_6_CYC (500U) // ms

typedef struct
{
	uint8_t Mp5_LKA_Mode : 2;                    //      Bits= 2 Factor= 1

	uint8_t Mp5_LKA_main_SW : 1;                 //      Bits= 1 Factor= 1

	uint8_t Mp5_ISA_Switch : 2;                  //      Bits= 2 Factor= 1

	uint8_t Mp5_TSR_Switch : 2;                  //      Bits= 2 Factor= 1

	uint8_t MP5_DriveModeRemSwitch : 1;          //      Bits= 1 Factor= 1

	uint8_t MFS_AVASSystemSwitch : 2;            //      Bits= 2 Factor= 1

	uint8_t MP5_EnergyReturnIntensionSet : 2;    //      Bits= 2 Factor= 1

	uint8_t MP5_SayHi : 2;                       //      Bits= 2 Factor= 1

	uint8_t MP5_SerchCar : 2;                    //      Bits= 2 Factor= 1

	uint8_t MP5_Open_Close : 2;                  //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_MP5_6_t;

uint32_t Unpack_BCAN_FBTC_MP5_6(BCAN_FBTC_MP5_6_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_MP5_6(BCAN_FBTC_MP5_6_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_MP5_TBOX_Time CAN Message (1242 0x4da)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_MP5_TBOX_Time_IDE (0U)
#define FBTC_MP5_TBOX_Time_DLC (8U)
#define FBTC_MP5_TBOX_Time_CANID (0x4da)
#define FBTC_MP5_TBOX_Time_CYC (1000U) // ms

typedef struct
{
	uint8_t MP5_TBOX_Time_Month : 4;             //      Bits= 4 Factor= 1

	uint8_t MP5_TBOX_Time_Valid : 1;             //      Bits= 1 Factor= 1

	uint8_t MP5_TBOX_Time_YearMark : 1;          //      Bits= 1 Factor= 1

	uint8_t MP5_TBOX_Time_Date : 5;              //      Bits= 5 Factor= 1

	uint8_t MP5_TBOX_Time_Hour : 5;              //      Bits= 5 Factor= 1

	uint8_t MP5_TBOX_Time_Minute : 6;            //      Bits= 6 Factor= 1

	uint8_t MP5_TBOX_Time_Second : 6;            //      Bits= 6 Factor= 1

	uint8_t MP5_TBOX_Time_Year : 8;              //      Bits= 8 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_MP5_TBOX_Time_t;

uint32_t Unpack_BCAN_FBTC_MP5_TBOX_Time(BCAN_FBTC_MP5_TBOX_Time_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_MP5_TBOX_Time(BCAN_FBTC_MP5_TBOX_Time_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_MP5_2 CAN Message (870 0x366)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_MP5_2_IDE (0U)
#define FBTC_MP5_2_DLC (8U)
#define FBTC_MP5_2_CANID (0x366)
#define FBTC_MP5_2_CYC (500U) // ms

typedef struct
{
	uint8_t MP5_HU_SlotUserSelected : 3;         //      Bits= 3 Factor= 1

	uint8_t MP5_WorkSt : 2;                      //      Bits= 2 Factor= 1

	uint8_t MP5_GearshiftRemindFunctEnaSwi : 2;  //      Bits= 2 Factor= 1

	uint8_t MP5_DDS_resetbutton_request : 1;     //      Bits= 1 Factor= 1

	uint8_t MP5_AutoWindLockSe : 1;              //      Bits= 1 Factor= 1

	uint8_t MP5_AutoWindUnlockSet : 1;           //      Bits= 1 Factor= 1

	uint8_t MP5_AutoWindKeyPressSet : 1;         //      Bits= 1 Factor= 1

	uint8_t MP5_ICStyle_Set : 3;                 //      Bits= 3 Factor= 1

	uint8_t MP5_Language_Set : 3;                //      Bits= 3 Factor= 1

	uint8_t MP5_IC_PersonalizedSet_right : 4;    //      Bits= 4 Factor= 1

	uint8_t MP5_IC_PersonalizedSet_left : 4;     //      Bits= 4 Factor= 1

	uint8_t MP5_PM2_5_EnableSwitch : 2;          //      Bits= 2 Factor= 1

	uint8_t MP5_HU_ULS_BSD_ACTIVATION : 2;       //      Bits= 2 Factor= 1

	uint8_t MP5_HU_ULS_FLK_ACTIVATION : 2;       //      Bits= 2 Factor= 1

	uint8_t MP5_BrightnessChange : 3;            //      Bits= 3 Factor= 1

	uint8_t MP5_ESCOFFSwitch : 2;                //      Bits= 2 Factor= 1

	uint8_t MP5_FCWSwitch : 2;                   //      Bits= 2 Factor= 1

	uint8_t MP5_AEBSwitch : 2;                   //      Bits= 2 Factor= 1

	uint8_t MP5_FCW_Sensitivity : 2;             //      Bits= 2 Factor= 1

	uint8_t MP5_AVHbutton : 2;                   //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_MP5_2_t;

uint32_t Unpack_BCAN_FBTC_MP5_2(BCAN_FBTC_MP5_2_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_MP5_2(BCAN_FBTC_MP5_2_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_AC1 CAN Message (802 0x322)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_AC1_IDE (0U)
#define FBTC_AC1_DLC (8U)
#define FBTC_AC1_CANID (0x322)
#define FBTC_AC1_CYC (100U) // ms

typedef struct
{
	uint8_t AC_AmbTemp : 8;                      //      Bits= 8 Factor= 1

	uint8_t AC_SystemOff : 1;                    //      Bits= 1 Factor= 1

	uint8_t AC_IntakeWindSt : 1;                 //      Bits= 1 Factor= 1

	uint8_t AC_RearWindowHeatReq : 1;            //      Bits= 1 Factor= 1

	uint8_t AC_BlowerWorkSt : 1;                 //      Bits= 1 Factor= 1

	uint8_t AC_ACCompressorReqSig : 2;           //      Bits= 2 Factor= 1

	uint8_t AC_AutoModeSt : 2;                   //      Bits= 2 Factor= 1

	uint8_t AC_BlowLvlSt : 4;                    //      Bits= 4 Factor= 1

	uint8_t AC_BlowMode : 3;                     //      Bits= 3 Factor= 1

	uint8_t BDC_AC_FrontDefrostMAXSt : 1;        //      Bits= 1 Factor= 1

	uint8_t AC_TempLevel : 5;                    //      Bits= 5 Factor= 1

	uint8_t AC_EvapTemp : 8;                     //      Bits= 8 Factor= 1

	uint8_t AC_AmbTempSensorDTC : 2;             //      Bits= 2 Factor= 1

	uint8_t AC_ACRunningStatus : 3;              //      Bits= 3 Factor= 1

	uint8_t AC_ACStatus : 2;                     //      Bits= 2 Factor= 1

	uint8_t AC_WindTemp : 2;                     //      Bits= 2 Factor= 1

	uint8_t AC_MP5DisplayPopupReq : 2;           //      Bits= 2 Factor= 1

	uint8_t AC_LED_AC : 2;                       //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_AC1_t;

uint32_t Unpack_BCAN_FBTC_AC1(BCAN_FBTC_AC1_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_AC1(BCAN_FBTC_AC1_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_IBCM6 CAN Message (833 0x341)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_IBCM6_IDE (0U)
#define FBTC_IBCM6_DLC (8U)
#define FBTC_IBCM6_CANID (0x341)
#define FBTC_IBCM6_CYC (100U) // ms

typedef struct
{
	uint16_t BCM_BattVolt : 10;                  //      Bits= 10 Factor= 1

	uint16_t BCM_BECB_BattCurrent : 10;          //      Bits= 10 Factor= 1

	uint8_t BCM_BECB_BattSOCStatus : 2;          //      Bits= 2 Factor= 1

	uint8_t BCM_BECB_BattSOC : 8;                //      Bits= 8 Factor= 1

	uint8_t BCM_BECB_Sensor_Config : 1;          //      Bits= 1 Factor= 1

	uint8_t BCM_BECB_BattSensorStatus : 7;       //      Bits= 7 Factor= 1

	uint8_t IBCM_SunshadCurCloseLockSt : 1;      //      Bits= 1 Factor= 1

	uint8_t IBCM_AtwsAlarmedType : 1;            //      Bits= 1 Factor= 1

	uint8_t IBCM_PanicType : 1;                  //      Bits= 1 Factor= 1

	uint8_t BCM_LowPowerWarning : 3;             //      Bits= 3 Factor= 1

	uint8_t BCM_CarMode : 2;                     //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_IBCM6_t;

uint32_t Unpack_BCAN_FBTC_IBCM6(BCAN_FBTC_IBCM6_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_IBCM6(BCAN_FBTC_IBCM6_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_IBCM3 CAN Message (828 0x33c)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_IBCM3_IDE (0U)
#define FBTC_IBCM3_DLC (8U)
#define FBTC_IBCM3_CANID (0x33c)
#define FBTC_IBCM3_CYC (100U) // ms

typedef struct
{
	uint8_t BCM_LowBeamFaultStatus : 2;          //      Bits= 2 Factor= 1

	uint8_t BCM_LampOnWarning : 1;               //      Bits= 1 Factor= 1

	uint8_t BCM_LowBeamSwitchStatus : 1;         //      Bits= 1 Factor= 1

	uint8_t BCM_BrakeSwitchSt : 1;               //      Bits= 1 Factor= 1

	uint8_t BCM_DoorLockSt : 1;                  //      Bits= 1 Factor= 1

	uint8_t BCM_IgnitionSt : 2;                  //      Bits= 2 Factor= 1

	uint8_t BCM_FrontWiperSwitchSt : 2;          //      Bits= 2 Factor= 1

	uint8_t BCM_EngLock : 1;                     //      Bits= 1 Factor= 1

	uint8_t BCM_BuzzerRequest : 5;               //      Bits= 5 Factor= 1

	uint8_t BCM_BackWiperWorkSt : 2;             //      Bits= 2 Factor= 1

	uint8_t BCM_BackWiperSwitchSt : 2;           //      Bits= 2 Factor= 1

	uint8_t BCM_FrontWiperParkst : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_ATWS_Sts : 3;                    //      Bits= 3 Factor= 1

	uint8_t BCM_ATWSFunctionStatus : 1;          //      Bits= 1 Factor= 1

	uint8_t BCM_BackWiperParkst : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_FrontWiperINTTimeStatus : 3;     //      Bits= 3 Factor= 1

	uint8_t BCM_PowerMode : 3;                   //      Bits= 3 Factor= 1

	uint8_t BCM_FrontFogFaultStatus : 2;         //      Bits= 2 Factor= 1

	uint8_t BCM_FrontFogSwtichStatus : 1;        //      Bits= 1 Factor= 1

	uint8_t BCM_HighBeamFaultStatus : 2;         //      Bits= 2 Factor= 1

	uint8_t BCM_HighBeamSwtichStatus : 1;        //      Bits= 1 Factor= 1

	uint8_t BCM_FRDoorLampStatus : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_FLDoorLampStatus : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_BrakeLampStatus : 2;             //      Bits= 2 Factor= 1

	uint8_t BCM_CHMSLStatus : 2;                 //      Bits= 2 Factor= 1

	uint8_t BCM_ReverseLampStatus : 2;           //      Bits= 2 Factor= 1

	uint8_t BCM_BackFogSwtichStatus : 2;         //      Bits= 2 Factor= 1

	uint8_t BCM_IlluminationLampStatus : 2;      //      Bits= 2 Factor= 1

	uint8_t BCM_TrunkLampStatus : 2;             //      Bits= 2 Factor= 1

	uint8_t BCM_LogLampStatus : 2;               //      Bits= 2 Factor= 1

	uint8_t BCM_WelcomeLampStatus : 2;           //      Bits= 2 Factor= 1

	uint8_t BCM_PositionLampFaultStatus : 2;     //      Bits= 2 Factor= 1

	uint8_t BCM_RightDayTimeRunningLampSta : 2;  //      Bits= 2 Factor= 1

	uint8_t BCM_LeftDayTimeRunningLampStatus : 2;//      Bits= 2 Factor= 1

	uint8_t BCM_BatterySaverOutputStatus : 2;    //      Bits= 2 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_IBCM3_t;

uint32_t Unpack_BCAN_FBTC_IBCM3(BCAN_FBTC_IBCM3_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_IBCM3(BCAN_FBTC_IBCM3_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_GW_ACU_Crash CAN Message (780 0x30c)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_GW_ACU_Crash_IDE (0U)
#define FCTB_GW_ACU_Crash_DLC (8U)
#define FCTB_GW_ACU_Crash_CANID (0x30c)
#define FCTB_GW_ACU_Crash_CYC (100U) // ms

typedef struct
{
	uint8_t RollingCounter30C : 4;               //      Bits= 4 Factor= 1

	uint8_t ACU_AirbagLampSts : 2;               //      Bits= 2 Factor= 1

	uint8_t ACU_Crashout : 2;                    //      Bits= 2 Factor= 1

	uint8_t ACU_PassengerBeltSwitchSig : 1;      //      Bits= 1 Factor= 1

	uint8_t ACU_DriverBeltSwitchSig : 1;         //      Bits= 1 Factor= 1

	uint8_t ACU_CrashoutValid : 1;               //      Bits= 1 Factor= 1

	uint8_t ACU_CheckSum_ACU : 8;                //      Bits= 8 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_GW_ACU_Crash_t;

uint32_t Unpack_BCAN_FCTB_GW_ACU_Crash(BCAN_FCTB_GW_ACU_Crash_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_GW_ACU_Crash(BCAN_FCTB_GW_ACU_Crash_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FBTC_IBCM2 CAN Message (570 0x23a)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FBTC_IBCM2_IDE (0U)
#define FBTC_IBCM2_DLC (8U)
#define FBTC_IBCM2_CANID (0x23a)
#define FBTC_IBCM2_CYC (40U) // ms

typedef struct
{
	uint8_t BCM_HighBeamStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_HazardLampSt : 1;                //      Bits= 1 Factor= 1

	uint8_t BCM_PositionLampSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RightligthFaultSt : 1;           //      Bits= 1 Factor= 1

	uint8_t BCM_RightligthSt : 1;                //      Bits= 1 Factor= 1

	uint8_t BCM_LetfligthFaultSt : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_LetfligthSt : 1;                 //      Bits= 1 Factor= 1

	uint8_t BCM_TrunkSt : 1;                     //      Bits= 1 Factor= 1

	uint8_t BCM_LRDoorSwitchSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RRDoorSwitchSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RFDoorSwitchSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_LFDoorSwitchSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_frontFogligthSt : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_BackFogligthSt : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_LowBeamStatus : 1;               //      Bits= 1 Factor= 1

	uint8_t BCM_RightTurnSwitchrSt : 2;          //      Bits= 2 Factor= 1

	uint8_t BCM_LeftTurnSwitchSt : 2;            //      Bits= 2 Factor= 1

	uint8_t BCM_Lock_LED_Output : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_AutoLockFunctionSt : 1;          //      Bits= 1 Factor= 1

	uint8_t BCM_RearWindowHeatSt : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_IntTrunkSwitch : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_FRTurnlightFbSt : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_RRTurnlightFbSt : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_FLTurnlightFbSt : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_RLTurnlightFbSt : 1;             //      Bits= 1 Factor= 1

	uint8_t BCM_LampWashSt : 1;                  //      Bits= 1 Factor= 1

	uint8_t BCM_ReverseLampSwitchSt : 2;         //      Bits= 2 Factor= 1

	uint8_t BCM_RecentlyLockType : 4;            //      Bits= 4 Factor= 1

	uint8_t BCM_RecentlyUnlockType : 4;          //      Bits= 4 Factor= 1

	uint8_t BCM_RLS_AUTO_SwitchSt : 1;           //      Bits= 1 Factor= 1

	uint8_t BCM_FrontWiperWorkSt : 2;            //      Bits= 2 Factor= 1

	uint8_t BCM_MirrorFoldSwitchSt : 2;          //      Bits= 2 Factor= 1

	uint8_t BCM_SunShadeStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RoofWindowStatus : 1;            //      Bits= 1 Factor= 1

	uint8_t BCM_RRWindowStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RFWindowStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_RLWindowStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_LFWindowStatus : 1;              //      Bits= 1 Factor= 1

	uint8_t BCM_TailgateUnlockInform : 1;        //      Bits= 1 Factor= 1

	uint8_t BCM_TailgateOpenSwitch : 1;          //      Bits= 1 Factor= 1

	uint8_t BCM_FrontWiper_AUTO : 2;             //      Bits= 2 Factor= 1

	uint8_t BCM_LowBeam_AUTO : 2;                //      Bits= 2 Factor= 1

	uint8_t Right_TurnLamp_Water_Control : 1;    //      Bits= 1 Factor= 1

	uint8_t Left_TurnLamp_Water_Control : 1;     //      Bits= 1 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FBTC_IBCM2_t;

uint32_t Unpack_BCAN_FBTC_IBCM2(BCAN_FBTC_IBCM2_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FBTC_IBCM2(BCAN_FBTC_IBCM2_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_GW_ESC7 CAN Message (1073 0x431)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_GW_ESC7_IDE (0U)
#define FCTB_GW_ESC7_DLC (8U)
#define FCTB_GW_ESC7_CANID (0x431)
#define FCTB_GW_ESC7_CYC (1000U) // ms

typedef struct
{
	uint8_t GW_ESC_ITPMSFrontRightPressWarn : 2; //      Bits= 2 Factor= 1

	uint8_t GW_ESC_ITPMSFrontLeftPressWarn : 2;  //      Bits= 2 Factor= 1

	uint8_t GW_ESC_ITPMSRearRightPressWarn : 2;  //      Bits= 2 Factor= 1

	uint8_t GW_ESC_ITPMSRearLeftPressWarn : 2;   //      Bits= 2 Factor= 1

	uint8_t GW_ESC_DDS_SystemStatus : 4;         //      Bits= 4 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_GW_ESC7_t;

uint32_t Unpack_BCAN_FCTB_GW_ESC7(BCAN_FCTB_GW_ESC7_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_GW_ESC7(BCAN_FCTB_GW_ESC7_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_IC_ESC2 CAN Message (160 0xa0)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_IC_ESC2_IDE (0U)
#define FCTB_IC_ESC2_DLC (8U)
#define FCTB_IC_ESC2_CANID (0xa0)
#define FCTB_IC_ESC2_CYC (10U) // ms

typedef struct
{
	uint16_t GW_ESC_BrakeOilPress : 11;          //      Bits= 11 Factor= 1

	uint8_t GW_ABS_WorkLable : 1;                //      Bits= 1 Factor= 1

	uint8_t GW_ESC_TCSCtlActive : 2;             //      Bits= 2 Factor= 1

	uint8_t GW_ESC_ABSAlarmSig : 1;              //      Bits= 1 Factor= 1

	uint8_t GW_ESC_VehSpdValidFlag : 1;          //      Bits= 1 Factor= 1

	uint8_t GW_ESC_EBDAlarmSig : 1;              //      Bits= 1 Factor= 1

	uint8_t GW_ESC_Brake_fluid_level_alarm : 1;  //      Bits= 1 Factor= 1

	uint16_t GW_ESC_VehSpd : 16;                 //      Bits= 16 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_IC_ESC2_t;

uint32_t Unpack_BCAN_FCTB_IC_ESC2(BCAN_FCTB_IC_ESC2_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_IC_ESC2(BCAN_FCTB_IC_ESC2_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);


/*
def @FCTB_IC_SAS_info CAN Message (165 0xa5)
+-------------------+--------+---------+
| Is Extended Frame | Length | Comment |
+-------------------+--------+---------+
|       False       |   8    |   None  |
+-------------------+--------+---------+
*/
#define FCTB_IC_SAS_info_IDE (0U)
#define FCTB_IC_SAS_info_DLC (8U)
#define FCTB_IC_SAS_info_CANID (0xa5)
#define FCTB_IC_SAS_info_CYC (10U) // ms

typedef struct
{
	int16_t GW_EPS_SAS_SteeringAngle : 16;       //  [-] Bits= 16 Factor= 1

	BCAN_FrameMonitor_t mon1;

}BCAN_FCTB_IC_SAS_info_t;

uint32_t Unpack_BCAN_FCTB_IC_SAS_info(BCAN_FCTB_IC_SAS_info_t* _message, const uint8_t _data[], uint8_t _dlc);
uint32_t Pack_BCAN_FCTB_IC_SAS_info(BCAN_FCTB_IC_SAS_info_t* _message, uint8_t* _data, uint8_t* _len, uint8_t* _ide);




/******** END OF FILE ********/
