/**
* @file         BCAN_monitor.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#include <stdint.h>
#include "BCAN_monitorutil.h"


void BCAN_monitor_FBTC_MP5_Mode(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_CBS2(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_IC_ESC_EPB1(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_IC_ESC3(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_IC_ESC6(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_CGW_VCU5(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_AC_Front2(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_MP5_6(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_MP5_TBOX_Time(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_MP5_2(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_AC1(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_IBCM6(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_IBCM3(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_GW_ACU_Crash(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FBTC_IBCM2(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_GW_ESC7(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_IC_ESC2(BCAN_FrameMonitor_t* _mon, uint32_t msgid);
void BCAN_monitor_FCTB_IC_SAS_info(BCAN_FrameMonitor_t* _mon, uint32_t msgid);


/******** END OF FILE ********/
