/**
* @file         BCAN_binutil.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#include "BCAN_definition.h"


typedef struct
{
	BCAN_FBTC_MP5_Mode_t FBTC_MP5_Mode;
	BCAN_FCTB_CBS2_t FCTB_CBS2;
	BCAN_FCTB_IC_ESC_EPB1_t FCTB_IC_ESC_EPB1;
	BCAN_FCTB_IC_ESC3_t FCTB_IC_ESC3;
	BCAN_FCTB_IC_ESC6_t FCTB_IC_ESC6;
	BCAN_FCTB_CGW_VCU5_t FCTB_CGW_VCU5;
	BCAN_FBTC_AC_Front2_t FBTC_AC_Front2;
	BCAN_FBTC_MP5_6_t FBTC_MP5_6;
	BCAN_FBTC_MP5_TBOX_Time_t FBTC_MP5_TBOX_Time;
	BCAN_FBTC_MP5_2_t FBTC_MP5_2;
	BCAN_FBTC_AC1_t FBTC_AC1;
	BCAN_FBTC_IBCM6_t FBTC_IBCM6;
	BCAN_FBTC_IBCM3_t FBTC_IBCM3;
	BCAN_FCTB_GW_ACU_Crash_t FCTB_GW_ACU_Crash;
	BCAN_FBTC_IBCM2_t FBTC_IBCM2;
	BCAN_FCTB_GW_ESC7_t FCTB_GW_ESC7;
	BCAN_FCTB_IC_ESC2_t FCTB_IC_ESC2;
	BCAN_FCTB_IC_SAS_info_t FCTB_IC_SAS_info;
} BCAN_msglist_t;

extern BCAN_msglist_t BCAN_msglist;

extern uint32_t BCAN_Transmit(BCAN_msglist_t* _message, uint8_t* _data, uint32_t _msgid, uint8_t* dlc_, uint8_t* _ide);

extern uint32_t BCAN_Receive(BCAN_msglist_t* _message, const uint8_t* _data, uint32_t _msgid, uint8_t dlc);



/******** END OF FILE ********/
