/**
* @file         CCAN_binutil.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#include "CCAN_definition.h"


typedef struct
{
	CCAN_FBTC_MP5_Mode_t FBTC_MP5_Mode;
	CCAN_FBTC_AC_Front2_t FBTC_AC_Front2;
	CCAN_FCTB_CBS2_t FCTB_CBS2;
	CCAN_FBTC_MP5_6_t FBTC_MP5_6;
	CCAN_FBTC_GW_MP5_2_t FBTC_GW_MP5_2;
	CCAN_FCTB_GW_VCUtoDisplay_t FCTB_GW_VCUtoDisplay;
	CCAN_FBTC_GW_AC1_t FBTC_GW_AC1;
	CCAN_FBTC_GW_MP5_TBOX_Time_t FBTC_GW_MP5_TBOX_Time;
	CCAN_FBTC_GW_IBCM6_t FBTC_GW_IBCM6;
	CCAN_FBTC_GW_IBCM3_t FBTC_GW_IBCM3;
	CCAN_FBTC_GW_IBCM2_t FBTC_GW_IBCM2;
	CCAN_FCTB_ACU_Crash_t FCTB_ACU_Crash;
	CCAN_FCTB_TAS_SAS_Info_t FCTB_TAS_SAS_Info;
	CCAN_FCTB_ESC_FPB1_t FCTB_ESC_FPB1;
	CCAN_FCTB_ESC7_t FCTB_ESC7;
	CCAN_FCTB_ESC6_t FCTB_ESC6;
	CCAN_FCTB_ESC3_t FCTB_ESC3;
	CCAN_FCTB_ESC2_t FCTB_ESC2;
} CCAN_msglist_t;

extern CCAN_msglist_t CCAN_msglist;

extern uint32_t CCAN_Transmit(CCAN_msglist_t* _message, uint8_t* _data, uint32_t _msgid, uint8_t* dlc_, uint8_t* _ide);

extern uint32_t CCAN_Receive(CCAN_msglist_t* _message, const uint8_t* _data, uint32_t _msgid, uint8_t dlc);



/******** END OF FILE ********/
