/**
* @file         CCAN_MsgParseAOP.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

extern void BeforeParse_CCAN_FCTB_ESC2(void);
extern void AfterParse_CCAN_FCTB_ESC2(void);

extern void BeforeParse_CCAN_FCTB_TAS_SAS_Info(void);
extern void AfterParse_CCAN_FCTB_TAS_SAS_Info(void);

extern void BeforeParse_CCAN_FCTB_ESC3(void);
extern void AfterParse_CCAN_FCTB_ESC3(void);

extern void BeforeParse_CCAN_FCTB_ESC6(void);
extern void AfterParse_CCAN_FCTB_ESC6(void);

extern void BeforeParse_CCAN_FBTC_GW_IBCM2(void);
extern void AfterParse_CCAN_FBTC_GW_IBCM2(void);

extern void BeforeParse_CCAN_FCTB_ACU_Crash(void);
extern void AfterParse_CCAN_FCTB_ACU_Crash(void);

extern void BeforeParse_CCAN_FCTB_ESC_FPB1(void);
extern void AfterParse_CCAN_FCTB_ESC_FPB1(void);

extern void BeforeParse_CCAN_FBTC_GW_AC1(void);
extern void AfterParse_CCAN_FBTC_GW_AC1(void);

extern void BeforeParse_CCAN_FBTC_GW_IBCM3(void);
extern void AfterParse_CCAN_FBTC_GW_IBCM3(void);

extern void BeforeParse_CCAN_FBTC_GW_IBCM6(void);
extern void AfterParse_CCAN_FBTC_GW_IBCM6(void);

extern void BeforeParse_CCAN_FCTB_GW_VCUtoDisplay(void);
extern void AfterParse_CCAN_FCTB_GW_VCUtoDisplay(void);

extern void BeforeParse_CCAN_FBTC_GW_MP5_2(void);
extern void AfterParse_CCAN_FBTC_GW_MP5_2(void);

extern void BeforeParse_CCAN_FBTC_AC_Front2(void);
extern void AfterParse_CCAN_FBTC_AC_Front2(void);

extern void BeforeParse_CCAN_FCTB_CBS2(void);
extern void AfterParse_CCAN_FCTB_CBS2(void);

extern void BeforeParse_CCAN_FBTC_MP5_6(void);
extern void AfterParse_CCAN_FBTC_MP5_6(void);

extern void BeforeParse_CCAN_FCTB_ESC7(void);
extern void AfterParse_CCAN_FCTB_ESC7(void);

extern void BeforeParse_CCAN_FBTC_GW_MP5_TBOX_Time(void);
extern void AfterParse_CCAN_FBTC_GW_MP5_TBOX_Time(void);

extern void BeforeParse_CCAN_FBTC_MP5_Mode(void);
extern void AfterParse_CCAN_FBTC_MP5_Mode(void);



/******** END OF FILE ********/
