/**
* @file         CCAN_monitor.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

#include <stdint.h>
#include "CCAN_monitorutil.h"


void CCAN_monitor_FBTC_MP5_Mode(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_AC_Front2(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_CBS2(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_MP5_6(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_MP5_2(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_GW_VCUtoDisplay(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_AC1(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_MP5_TBOX_Time(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_IBCM6(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_IBCM3(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FBTC_GW_IBCM2(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ACU_Crash(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_TAS_SAS_Info(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ESC_FPB1(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ESC7(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ESC6(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ESC3(CCAN_FrameMonitor_t* _mon, uint32_t msgid);
void CCAN_monitor_FCTB_ESC2(CCAN_FrameMonitor_t* _mon, uint32_t msgid);


/******** END OF FILE ********/
