/**
* @file         CCAN_MsgCycAOP.h
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#pragma once

extern void CCAN_TimeoutFunc_FCTB_ESC2(void);
extern void CCAN_TimingFuncFCTB_ESC2(void);
extern void CCAN_CycleOverFuncFCTB_ESC2(void);

extern void CCAN_TimeoutFunc_FCTB_TAS_SAS_Info(void);
extern void CCAN_TimingFuncFCTB_TAS_SAS_Info(void);
extern void CCAN_CycleOverFuncFCTB_TAS_SAS_Info(void);

extern void CCAN_TimeoutFunc_FCTB_ESC3(void);
extern void CCAN_TimingFuncFCTB_ESC3(void);
extern void CCAN_CycleOverFuncFCTB_ESC3(void);

extern void CCAN_TimeoutFunc_FCTB_ESC6(void);
extern void CCAN_TimingFuncFCTB_ESC6(void);
extern void CCAN_CycleOverFuncFCTB_ESC6(void);

extern void CCAN_TimeoutFunc_FBTC_GW_IBCM2(void);
extern void CCAN_TimingFuncFBTC_GW_IBCM2(void);
extern void CCAN_CycleOverFuncFBTC_GW_IBCM2(void);

extern void CCAN_TimeoutFunc_FCTB_ACU_Crash(void);
extern void CCAN_TimingFuncFCTB_ACU_Crash(void);
extern void CCAN_CycleOverFuncFCTB_ACU_Crash(void);

extern void CCAN_TimeoutFunc_FCTB_ESC_FPB1(void);
extern void CCAN_TimingFuncFCTB_ESC_FPB1(void);
extern void CCAN_CycleOverFuncFCTB_ESC_FPB1(void);

extern void CCAN_TimeoutFunc_FBTC_GW_AC1(void);
extern void CCAN_TimingFuncFBTC_GW_AC1(void);
extern void CCAN_CycleOverFuncFBTC_GW_AC1(void);

extern void CCAN_TimeoutFunc_FBTC_GW_IBCM3(void);
extern void CCAN_TimingFuncFBTC_GW_IBCM3(void);
extern void CCAN_CycleOverFuncFBTC_GW_IBCM3(void);

extern void CCAN_TimeoutFunc_FBTC_GW_IBCM6(void);
extern void CCAN_TimingFuncFBTC_GW_IBCM6(void);
extern void CCAN_CycleOverFuncFBTC_GW_IBCM6(void);

extern void CCAN_TimeoutFunc_FCTB_GW_VCUtoDisplay(void);
extern void CCAN_TimingFuncFCTB_GW_VCUtoDisplay(void);
extern void CCAN_CycleOverFuncFCTB_GW_VCUtoDisplay(void);

extern void CCAN_TimeoutFunc_FBTC_GW_MP5_2(void);
extern void CCAN_TimingFuncFBTC_GW_MP5_2(void);
extern void CCAN_CycleOverFuncFBTC_GW_MP5_2(void);

extern void CCAN_TimeoutFunc_FBTC_AC_Front2(void);
extern void CCAN_TimingFuncFBTC_AC_Front2(void);
extern void CCAN_CycleOverFuncFBTC_AC_Front2(void);

extern void CCAN_TimeoutFunc_FCTB_CBS2(void);
extern void CCAN_TimingFuncFCTB_CBS2(void);
extern void CCAN_CycleOverFuncFCTB_CBS2(void);

extern void CCAN_TimeoutFunc_FBTC_MP5_6(void);
extern void CCAN_TimingFuncFBTC_MP5_6(void);
extern void CCAN_CycleOverFuncFBTC_MP5_6(void);

extern void CCAN_TimeoutFunc_FCTB_ESC7(void);
extern void CCAN_TimingFuncFCTB_ESC7(void);
extern void CCAN_CycleOverFuncFCTB_ESC7(void);

extern void CCAN_TimeoutFunc_FBTC_GW_MP5_TBOX_Time(void);
extern void CCAN_TimingFuncFBTC_GW_MP5_TBOX_Time(void);
extern void CCAN_CycleOverFuncFBTC_GW_MP5_TBOX_Time(void);

extern void CCAN_TimeoutFunc_FBTC_MP5_Mode(void);
extern void CCAN_TimingFuncFBTC_MP5_Mode(void);
extern void CCAN_CycleOverFuncFBTC_MP5_Mode(void);



/******** END OF FILE ********/
