/**
* @file         CCAN_definition.c
* @author       96400
* @note         The code is automatically generated by GatewayTool
* @version      V1.0.0
* @date         2023.01.12, 11:03:06
* @brief        
* @attention    
**/

#include <string.h>
#include "CCAN_definition.h"
#include "CCAN_MsgParseAOP.h"


/*
Message Name: FBTC_MP5_Mode
Message Id: 0x4fd (1277)
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|      Signal Name       | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| MP5_VehiclePowerSwitch |     6     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|    MP5_DriveModeSET    |     2     |   4    | big_endian |       False        |   1    |   0    | None |   None   |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_MP5_Mode(CCAN_FBTC_MP5_Mode_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_MP5_Mode(void);
	_message->MP5_VehiclePowerSwitch = (_data[0] & 0xC0U) >> 6;
	_message->MP5_DriveModeSET = (_data[0] & 0x3CU) >> 2;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_MP5_Mode_DLC);
	CCAN_monitor_FBTC_MP5_Mode(&_message->mon1, FBTC_MP5_Mode_CANID);

AfterParse_CCAN_FBTC_MP5_Mode(void);
	return FBTC_MP5_Mode_CANID;
}

uint32_t Pack_CCAN_FBTC_MP5_Mode(CCAN_FBTC_MP5_Mode_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->MP5_VehiclePowerSwitch << 6;
	_data[0] |= _message->MP5_DriveModeSET << 2;

	*_dlc = FBTC_MP5_Mode_DLC;
	*_ide = FBTC_MP5_Mode_IDE;
	return FBTC_MP5_Mode_CANID;
}

/*
Message Name: FBTC_AC_Front2
Message Id: 0x37c (892)
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|        Signal Name         | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|        AC_InCarTemp        |     0     |   8    | big_endian |       False        |   1    |   0    | None |   None   |
|   AC_FrontEvapTempTarget   |     8     |   8    | big_endian |       False        |   1    |   0    | None |   None   |
|     AC_FrontACStartReq     |     40    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| AC_FrontHeaterInletTempSet |     56    |   16   | big_endian |       False        |   1    |   0    | None |   None   |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_AC_Front2(CCAN_FBTC_AC_Front2_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_AC_Front2(void);
	_message->AC_InCarTemp = _data[0] & 0xFFU;
	_message->AC_FrontEvapTempTarget = _data[1] & 0xFFU;
	_message->AC_FrontACStartReq = _data[5] & 0x03U;
	_message->AC_FrontHeaterInletTempSet = (_data[6] & 0xFFU) << 8 | (_data[7] & 0xFFU);

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_AC_Front2_DLC);
	CCAN_monitor_FBTC_AC_Front2(&_message->mon1, FBTC_AC_Front2_CANID);

AfterParse_CCAN_FBTC_AC_Front2(void);
	return FBTC_AC_Front2_CANID;
}

uint32_t Pack_CCAN_FBTC_AC_Front2(CCAN_FBTC_AC_Front2_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->AC_InCarTemp;
	_data[1] |= _message->AC_FrontEvapTempTarget;
	_data[5] |= _message->AC_FrontACStartReq;
	_data[6] |= (_message->AC_FrontHeaterInletTempSet >> 8) & 0xFFU;
	_data[7] |= _message->AC_FrontHeaterInletTempSet & 0xFFU;

	*_dlc = FBTC_AC_Front2_DLC;
	*_ide = FBTC_AC_Front2_IDE;
	return FBTC_AC_Front2_CANID;
}

/*
Message Name: FCTB_CBS2
Message Id: 0x3ff (1023)
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|       Signal Name        | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|    CWB_DimmingSwitch     |     5     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   CWB_PreWashingSwitch   |     3     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      CWB_TurnSwitch      |     0     |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|   CWB_FrontWiperSwitch   |     13    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
| CWB_FrontWiperAdjustment |     10    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_CBS2(CCAN_FCTB_CBS2_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_CBS2(void);
	_message->CWB_DimmingSwitch = (_data[0] & 0x60U) >> 5;
	_message->CWB_PreWashingSwitch = (_data[0] & 0x18U) >> 3;
	_message->CWB_TurnSwitch = _data[0] & 0x07U;
	_message->CWB_FrontWiperSwitch = (_data[1] & 0xE0U) >> 5;
	_message->CWB_FrontWiperAdjustment = (_data[1] & 0x1CU) >> 2;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_CBS2_DLC);
	CCAN_monitor_FCTB_CBS2(&_message->mon1, FCTB_CBS2_CANID);

AfterParse_CCAN_FCTB_CBS2(void);
	return FCTB_CBS2_CANID;
}

uint32_t Pack_CCAN_FCTB_CBS2(CCAN_FCTB_CBS2_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->CWB_DimmingSwitch << 5;
	_data[0] |= _message->CWB_PreWashingSwitch << 3;
	_data[0] |= _message->CWB_TurnSwitch;
	_data[1] |= _message->CWB_FrontWiperSwitch << 5;
	_data[1] |= _message->CWB_FrontWiperAdjustment << 2;

	*_dlc = FCTB_CBS2_DLC;
	*_ide = FCTB_CBS2_IDE;
	return FCTB_CBS2_CANID;
}

/*
Message Name: FBTC_MP5_6
Message Id: 0x413 (1043)
+------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|         Signal Name          | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|         Mp5_LKA_Mode         |     6     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|       Mp5_LKA_main_SW        |     5     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|        Mp5_ISA_Switch        |     3     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|        Mp5_TSRSwitch         |     1     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|    MP5_DriveModeRemSwitch    |     0     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     MFS_AVASSystemSwitch     |     18    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| MP5_EnergyReturnIntensionSet |     16    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|          MP5_SayHi           |     60    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|         MP5_SerchCar         |     58    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|        MP5_Open_Close        |     56    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
+------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_MP5_6(CCAN_FBTC_MP5_6_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_MP5_6(void);
	_message->Mp5_LKA_Mode = (_data[0] & 0xC0U) >> 6;
	_message->Mp5_LKA_main_SW = (_data[0] & 0x20U) >> 5;
	_message->Mp5_ISA_Switch = (_data[0] & 0x18U) >> 3;
	_message->Mp5_TSRSwitch = (_data[0] & 0x06U) >> 1;
	_message->MP5_DriveModeRemSwitch = _data[0] & 0x01U;
	_message->MFS_AVASSystemSwitch = (_data[2] & 0x0CU) >> 2;
	_message->MP5_EnergyReturnIntensionSet = _data[2] & 0x03U;
	_message->MP5_SayHi = (_data[7] & 0x30U) >> 4;
	_message->MP5_SerchCar = (_data[7] & 0x0CU) >> 2;
	_message->MP5_Open_Close = _data[7] & 0x03U;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_MP5_6_DLC);
	CCAN_monitor_FBTC_MP5_6(&_message->mon1, FBTC_MP5_6_CANID);

AfterParse_CCAN_FBTC_MP5_6(void);
	return FBTC_MP5_6_CANID;
}

uint32_t Pack_CCAN_FBTC_MP5_6(CCAN_FBTC_MP5_6_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->Mp5_LKA_Mode << 6;
	_data[0] |= _message->Mp5_LKA_main_SW << 5;
	_data[0] |= _message->Mp5_ISA_Switch << 3;
	_data[0] |= _message->Mp5_TSRSwitch << 1;
	_data[0] |= _message->MP5_DriveModeRemSwitch;
	_data[2] |= _message->MFS_AVASSystemSwitch << 2;
	_data[2] |= _message->MP5_EnergyReturnIntensionSet;
	_data[7] |= _message->MP5_SayHi << 4;
	_data[7] |= _message->MP5_SerchCar << 2;
	_data[7] |= _message->MP5_Open_Close;

	*_dlc = FBTC_MP5_6_DLC;
	*_ide = FBTC_MP5_6_IDE;
	return FBTC_MP5_6_CANID;
}

/*
Message Name: FBTC_GW_MP5_2
Message Id: 0x366 (870)
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|          Signal Name          | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|    MP5_HU_SlotUserSelected    |     5     |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|           MP5_WorkSt          |     3     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| MP5_GearshiftRemindFunctionES |     1     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  MP5_DDS_resetbutton_request  |     0     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|       MP5_AutoWindLockSe      |     10    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     MP5_AutoWindUnlockSet     |     9     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    MP5_AutoWindKeyPressSet    |     8     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|        MP5_Language_Set       |     16    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|     MP5_PM2_5_EnableSwitch    |     38    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   MP5_HU_ULS_BSD_ACTIVATION   |     34    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   MP5_HU_ULS_FLK_ACTIVATION   |     32    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      MP5_BrightnessChange     |     40    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|        MP5_ESCOFFSwitch       |     54    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|         MP5_FCWSwitch         |     50    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|         MP5_AEBSwitch         |     48    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      MP5_FCW_Sensitivity      |     58    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|         MP5_AVHbutton         |     56    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_MP5_2(CCAN_FBTC_GW_MP5_2_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_MP5_2(void);
	_message->MP5_HU_SlotUserSelected = (_data[0] & 0xE0U) >> 5;
	_message->MP5_WorkSt = (_data[0] & 0x18U) >> 3;
	_message->MP5_GearshiftRemindFunctionES = (_data[0] & 0x06U) >> 1;
	_message->MP5_DDS_resetbutton_request = _data[0] & 0x01U;
	_message->MP5_AutoWindLockSe = (_data[1] & 0x04U) >> 2;
	_message->MP5_AutoWindUnlockSet = (_data[1] & 0x02U) >> 1;
	_message->MP5_AutoWindKeyPressSet = _data[1] & 0x01U;
	_message->MP5_Language_Set = _data[2] & 0x07U;
	_message->MP5_PM2_5_EnableSwitch = (_data[4] & 0xC0U) >> 6;
	_message->MP5_HU_ULS_BSD_ACTIVATION = (_data[4] & 0x0CU) >> 2;
	_message->MP5_HU_ULS_FLK_ACTIVATION = _data[4] & 0x03U;
	_message->MP5_BrightnessChange = _data[5] & 0x07U;
	_message->MP5_ESCOFFSwitch = (_data[6] & 0xC0U) >> 6;
	_message->MP5_FCWSwitch = (_data[6] & 0x0CU) >> 2;
	_message->MP5_AEBSwitch = _data[6] & 0x03U;
	_message->MP5_FCW_Sensitivity = (_data[7] & 0x0CU) >> 2;
	_message->MP5_AVHbutton = _data[7] & 0x03U;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_MP5_2_DLC);
	CCAN_monitor_FBTC_GW_MP5_2(&_message->mon1, FBTC_GW_MP5_2_CANID);

AfterParse_CCAN_FBTC_GW_MP5_2(void);
	return FBTC_GW_MP5_2_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_MP5_2(CCAN_FBTC_GW_MP5_2_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->MP5_HU_SlotUserSelected << 5;
	_data[0] |= _message->MP5_WorkSt << 3;
	_data[0] |= _message->MP5_GearshiftRemindFunctionES << 1;
	_data[0] |= _message->MP5_DDS_resetbutton_request;
	_data[1] |= _message->MP5_AutoWindLockSe << 2;
	_data[1] |= _message->MP5_AutoWindUnlockSet << 1;
	_data[1] |= _message->MP5_AutoWindKeyPressSet;
	_data[2] |= _message->MP5_Language_Set;
	_data[4] |= _message->MP5_PM2_5_EnableSwitch << 6;
	_data[4] |= _message->MP5_HU_ULS_BSD_ACTIVATION << 2;
	_data[4] |= _message->MP5_HU_ULS_FLK_ACTIVATION;
	_data[5] |= _message->MP5_BrightnessChange;
	_data[6] |= _message->MP5_ESCOFFSwitch << 6;
	_data[6] |= _message->MP5_FCWSwitch << 2;
	_data[6] |= _message->MP5_AEBSwitch;
	_data[7] |= _message->MP5_FCW_Sensitivity << 2;
	_data[7] |= _message->MP5_AVHbutton;

	*_dlc = FBTC_GW_MP5_2_DLC;
	*_ide = FBTC_GW_MP5_2_IDE;
	return FBTC_GW_MP5_2_CANID;
}

/*
Message Name: FCTB_GW_VCUtoDisplay
Message Id: 0x355 (853)
+--------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|          Signal Name           | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+--------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|       VCU_DrivingPermit        |     13    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|            VCU_Gear            |     10    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|     VCU_SystemFaultWarning     |     9     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| VCU_PerformanceLimitedWarning  |     8     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     VCU_PumpInvalidWarning     |     22    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|       VCU_CruisingRange        |     28    |   10   | big_endian |       False        |   1    |   0    | None |   None   |
|       VCU_ParkLockStatus       |     26    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  VCU_EnergyRecoveryGearSwitch  |     42    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|         VCU_DCDCworkSt         |     40    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| VCU_BrakeEnergyReturnIntension |     56    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+--------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_GW_VCUtoDisplay(CCAN_FCTB_GW_VCUtoDisplay_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_GW_VCUtoDisplay(void);
	_message->VCU_DrivingPermit = (_data[1] & 0x20U) >> 5;
	_message->VCU_Gear = (_data[1] & 0x1CU) >> 2;
	_message->VCU_SystemFaultWarning = (_data[1] & 0x02U) >> 1;
	_message->VCU_PerformanceLimitedWarning = _data[1] & 0x01U;
	_message->VCU_PumpInvalidWarning = (_data[2] & 0xC0U) >> 6;
	_message->VCU_CruisingRange = (_data[2] & 0x3FU) << 4 | (_data[3] & 0xF0U) >> 4;
	_message->VCU_ParkLockStatus = (_data[3] & 0x0CU) >> 2;
	_message->VCU_EnergyRecoveryGearSwitch = (_data[5] & 0x1CU) >> 2;
	_message->VCU_DCDCworkSt = _data[5] & 0x03U;
	_message->VCU_BrakeEnergyReturnIntension = _data[7] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_GW_VCUtoDisplay_DLC);
	CCAN_monitor_FCTB_GW_VCUtoDisplay(&_message->mon1, FCTB_GW_VCUtoDisplay_CANID);

AfterParse_CCAN_FCTB_GW_VCUtoDisplay(void);
	return FCTB_GW_VCUtoDisplay_CANID;
}

uint32_t Pack_CCAN_FCTB_GW_VCUtoDisplay(CCAN_FCTB_GW_VCUtoDisplay_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[1] |= _message->VCU_DrivingPermit << 5;
	_data[1] |= _message->VCU_Gear << 2;
	_data[1] |= _message->VCU_SystemFaultWarning << 1;
	_data[1] |= _message->VCU_PerformanceLimitedWarning;
	_data[2] |= _message->VCU_PumpInvalidWarning << 6;
	_data[2] |= (_message->VCU_CruisingRange >> 4) & 0x3FU;
	_data[3] |= (_message->VCU_CruisingRange << 4) & 0xF0U;
	_data[3] |= _message->VCU_ParkLockStatus << 2;
	_data[5] |= _message->VCU_EnergyRecoveryGearSwitch << 2;
	_data[5] |= _message->VCU_DCDCworkSt;
	_data[7] |= _message->VCU_BrakeEnergyReturnIntension;

	*_dlc = FCTB_GW_VCUtoDisplay_DLC;
	*_ide = FCTB_GW_VCUtoDisplay_IDE;
	return FCTB_GW_VCUtoDisplay_CANID;
}

/*
Message Name: FBTC_GW_AC1
Message Id: 0x322 (802)
+-------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| Signal Name | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+-------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|  AC_AmbTemp |     0     |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+-------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_AC1(CCAN_FBTC_GW_AC1_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_AC1(void);
	_message->AC_AmbTemp = _data[0] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_AC1_DLC);
	CCAN_monitor_FBTC_GW_AC1(&_message->mon1, FBTC_GW_AC1_CANID);

AfterParse_CCAN_FBTC_GW_AC1(void);
	return FBTC_GW_AC1_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_AC1(CCAN_FBTC_GW_AC1_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->AC_AmbTemp;

	*_dlc = FBTC_GW_AC1_DLC;
	*_ide = FBTC_GW_AC1_IDE;
	return FBTC_GW_AC1_CANID;
}

/*
Message Name: FBTC_GW_MP5_TBOX_Time
Message Id: 0x4da (1242)
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|      Signal Name       | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|  MP5_TBOX_Time_Month   |     4     |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|  MP5_TBOX_Time_Valid   |     15    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| MP5_TBOX_Time_YearMark |     14    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   MP5_TBOX_Time_Date   |     8     |   5    | big_endian |       False        |   1    |   0    | None |   None   |
|   MP5_TBOX_Time_Hour   |     16    |   5    | big_endian |       False        |   1    |   0    | None |   None   |
|  MP5_TBOX_Time_Minute  |     24    |   6    | big_endian |       False        |   1    |   0    | None |   None   |
|  MP5_TBOX_Time_Second  |     32    |   6    | big_endian |       False        |   1    |   0    | None |   None   |
|   MP5_TBOX_Time_Year   |     40    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_MP5_TBOX_Time(CCAN_FBTC_GW_MP5_TBOX_Time_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_MP5_TBOX_Time(void);
	_message->MP5_TBOX_Time_Month = (_data[0] & 0xF0U) >> 4;
	_message->MP5_TBOX_Time_Valid = (_data[1] & 0x80U) >> 7;
	_message->MP5_TBOX_Time_YearMark = (_data[1] & 0x40U) >> 6;
	_message->MP5_TBOX_Time_Date = _data[1] & 0x1FU;
	_message->MP5_TBOX_Time_Hour = _data[2] & 0x1FU;
	_message->MP5_TBOX_Time_Minute = _data[3] & 0x3FU;
	_message->MP5_TBOX_Time_Second = _data[4] & 0x3FU;
	_message->MP5_TBOX_Time_Year = _data[5] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_MP5_TBOX_Time_DLC);
	CCAN_monitor_FBTC_GW_MP5_TBOX_Time(&_message->mon1, FBTC_GW_MP5_TBOX_Time_CANID);

AfterParse_CCAN_FBTC_GW_MP5_TBOX_Time(void);
	return FBTC_GW_MP5_TBOX_Time_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_MP5_TBOX_Time(CCAN_FBTC_GW_MP5_TBOX_Time_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->MP5_TBOX_Time_Month << 4;
	_data[1] |= _message->MP5_TBOX_Time_Valid << 7;
	_data[1] |= _message->MP5_TBOX_Time_YearMark << 6;
	_data[1] |= _message->MP5_TBOX_Time_Date;
	_data[2] |= _message->MP5_TBOX_Time_Hour;
	_data[3] |= _message->MP5_TBOX_Time_Minute;
	_data[4] |= _message->MP5_TBOX_Time_Second;
	_data[5] |= _message->MP5_TBOX_Time_Year;

	*_dlc = FBTC_GW_MP5_TBOX_Time_DLC;
	*_ide = FBTC_GW_MP5_TBOX_Time_IDE;
	return FBTC_GW_MP5_TBOX_Time_CANID;
}

/*
Message Name: FBTC_GW_IBCM6
Message Id: 0x341 (833)
+--------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| Signal Name  | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+--------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| BCM_BattVolt |     14    |   10   | big_endian |       False        |   1    |   0    | None |   None   |
+--------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_IBCM6(CCAN_FBTC_GW_IBCM6_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_IBCM6(void);
	_message->BCM_BattVolt = (_data[0] & 0xFFU) << 2 | (_data[1] & 0xC0U) >> 6;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_IBCM6_DLC);
	CCAN_monitor_FBTC_GW_IBCM6(&_message->mon1, FBTC_GW_IBCM6_CANID);

AfterParse_CCAN_FBTC_GW_IBCM6(void);
	return FBTC_GW_IBCM6_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_IBCM6(CCAN_FBTC_GW_IBCM6_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= (_message->BCM_BattVolt >> 2) & 0xFFU;
	_data[1] |= (_message->BCM_BattVolt << 2) & 0xC0U;

	*_dlc = FBTC_GW_IBCM6_DLC;
	*_ide = FBTC_GW_IBCM6_IDE;
	return FBTC_GW_IBCM6_CANID;
}

/*
Message Name: FBTC_GW_IBCM3
Message Id: 0x33c (828)
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|      Signal Name       | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|     BCM_DoorLockSt     |     2     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     BCM_IgnitionSt     |     0     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| BCM_FrontWiperSwitchSt |     14    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_BackWiperParkst   |     30    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_BrakeLampStatus   |     46    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_CHMSLStatus     |     44    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_IBCM3(CCAN_FBTC_GW_IBCM3_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_IBCM3(void);
	_message->BCM_DoorLockSt = (_data[0] & 0x04U) >> 2;
	_message->BCM_IgnitionSt = _data[0] & 0x03U;
	_message->BCM_FrontWiperSwitchSt = (_data[1] & 0xC0U) >> 6;
	_message->BCM_BackWiperParkst = (_data[3] & 0x40U) >> 6;
	_message->BCM_BrakeLampStatus = (_data[5] & 0xC0U) >> 6;
	_message->BCM_CHMSLStatus = (_data[5] & 0x30U) >> 4;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_IBCM3_DLC);
	CCAN_monitor_FBTC_GW_IBCM3(&_message->mon1, FBTC_GW_IBCM3_CANID);

AfterParse_CCAN_FBTC_GW_IBCM3(void);
	return FBTC_GW_IBCM3_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_IBCM3(CCAN_FBTC_GW_IBCM3_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->BCM_DoorLockSt << 2;
	_data[0] |= _message->BCM_IgnitionSt;
	_data[1] |= _message->BCM_FrontWiperSwitchSt << 6;
	_data[3] |= _message->BCM_BackWiperParkst << 6;
	_data[5] |= _message->BCM_BrakeLampStatus << 6;
	_data[5] |= _message->BCM_CHMSLStatus << 4;

	*_dlc = FBTC_GW_IBCM3_DLC;
	*_ide = FBTC_GW_IBCM3_IDE;
	return FBTC_GW_IBCM3_CANID;
}

/*
Message Name: FBTC_GW_IBCM2
Message Id: 0x23a (570)
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|       Signal Name        | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|    BCM_HighBeamStatus    |     7     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     BCM_HazardLampSt     |     6     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_PositionLampSt    |     5     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_RightligthFaultSt   |     4     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     BCM_RightligthSt     |     3     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_LetfligthFaultSt   |     2     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     BCM_LetfligthSt      |     1     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|       BCM_TrunkSt        |     0     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_FuleTap_LockStatus  |     15    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_LRDoorSwitchSt    |     14    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_RRDoorSwitchSt    |     13    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_RFDoorSwitchSt    |     12    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_LFDoorSwitchSt    |     11    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_frontFogligthSt    |     10    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_BackFogligthSt    |     9     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_LowBeamStatus     |     8     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_RightTurnSwitchrSt  |     22    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_LeftTurnSwitchSt   |     20    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_Lock_LED_Output    |     19    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_AutoLockFunctionSt  |     18    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_RearWindowHeatSt   |     17    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_FRTurnlightFbSt    |     31    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_RRTurnlightFbSt    |     30    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_FLTurnlightFbSt    |     29    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_RLTurnlightFbSt    |     28    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      BCM_LampWashSt      |     27    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| BCM_EngHoodUnlockWarming |     26    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| BCM_ReverseLampSwitchSt  |     24    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_RecentlyLockType   |     36    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_RecentlyUnlockType  |     32    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_RLS_AUTO_SwitchSt   |     46    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_FollowMeHomeSt    |     42    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_FrontWiperWorkSt   |     40    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_MirrorFoldSwitchSt  |     54    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_SunShadeStatus    |     53    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_RoofWindowStatus   |     52    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_RRWindowStatus    |     51    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_RFWindowStatus    |     50    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_RLWindowStatus    |     49    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    BCM_LFWindowStatus    |     48    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| BCM_TailgateUnlockInform |     63    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  BCM_TailgateOpenSwitch  |     62    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   BCM_FrontWiper_AUTO    |     60    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|     BCM_LowBeam_AUTO     |     58    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
+--------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FBTC_GW_IBCM2(CCAN_FBTC_GW_IBCM2_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FBTC_GW_IBCM2(void);
	_message->BCM_HighBeamStatus = (_data[0] & 0x80U) >> 7;
	_message->BCM_HazardLampSt = (_data[0] & 0x40U) >> 6;
	_message->BCM_PositionLampSt = (_data[0] & 0x20U) >> 5;
	_message->BCM_RightligthFaultSt = (_data[0] & 0x10U) >> 4;
	_message->BCM_RightligthSt = (_data[0] & 0x08U) >> 3;
	_message->BCM_LetfligthFaultSt = (_data[0] & 0x04U) >> 2;
	_message->BCM_LetfligthSt = (_data[0] & 0x02U) >> 1;
	_message->BCM_TrunkSt = _data[0] & 0x01U;
	_message->BCM_FuleTap_LockStatus = (_data[1] & 0x80U) >> 7;
	_message->BCM_LRDoorSwitchSt = (_data[1] & 0x40U) >> 6;
	_message->BCM_RRDoorSwitchSt = (_data[1] & 0x20U) >> 5;
	_message->BCM_RFDoorSwitchSt = (_data[1] & 0x10U) >> 4;
	_message->BCM_LFDoorSwitchSt = (_data[1] & 0x08U) >> 3;
	_message->BCM_frontFogligthSt = (_data[1] & 0x04U) >> 2;
	_message->BCM_BackFogligthSt = (_data[1] & 0x02U) >> 1;
	_message->BCM_LowBeamStatus = _data[1] & 0x01U;
	_message->BCM_RightTurnSwitchrSt = (_data[2] & 0xC0U) >> 6;
	_message->BCM_LeftTurnSwitchSt = (_data[2] & 0x30U) >> 4;
	_message->BCM_Lock_LED_Output = (_data[2] & 0x08U) >> 3;
	_message->BCM_AutoLockFunctionSt = (_data[2] & 0x04U) >> 2;
	_message->BCM_RearWindowHeatSt = (_data[2] & 0x02U) >> 1;
	_message->BCM_FRTurnlightFbSt = (_data[3] & 0x80U) >> 7;
	_message->BCM_RRTurnlightFbSt = (_data[3] & 0x40U) >> 6;
	_message->BCM_FLTurnlightFbSt = (_data[3] & 0x20U) >> 5;
	_message->BCM_RLTurnlightFbSt = (_data[3] & 0x10U) >> 4;
	_message->BCM_LampWashSt = (_data[3] & 0x08U) >> 3;
	_message->BCM_EngHoodUnlockWarming = (_data[3] & 0x04U) >> 2;
	_message->BCM_ReverseLampSwitchSt = _data[3] & 0x03U;
	_message->BCM_RecentlyLockType = (_data[4] & 0xF0U) >> 4;
	_message->BCM_RecentlyUnlockType = _data[4] & 0x0FU;
	_message->BCM_RLS_AUTO_SwitchSt = (_data[5] & 0x40U) >> 6;
	_message->BCM_FollowMeHomeSt = (_data[5] & 0x3CU) >> 2;
	_message->BCM_FrontWiperWorkSt = _data[5] & 0x03U;
	_message->BCM_MirrorFoldSwitchSt = (_data[6] & 0xC0U) >> 6;
	_message->BCM_SunShadeStatus = (_data[6] & 0x20U) >> 5;
	_message->BCM_RoofWindowStatus = (_data[6] & 0x10U) >> 4;
	_message->BCM_RRWindowStatus = (_data[6] & 0x08U) >> 3;
	_message->BCM_RFWindowStatus = (_data[6] & 0x04U) >> 2;
	_message->BCM_RLWindowStatus = (_data[6] & 0x02U) >> 1;
	_message->BCM_LFWindowStatus = _data[6] & 0x01U;
	_message->BCM_TailgateUnlockInform = (_data[7] & 0x80U) >> 7;
	_message->BCM_TailgateOpenSwitch = (_data[7] & 0x40U) >> 6;
	_message->BCM_FrontWiper_AUTO = (_data[7] & 0x30U) >> 4;
	_message->BCM_LowBeam_AUTO = (_data[7] & 0x0CU) >> 2;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FBTC_GW_IBCM2_DLC);
	CCAN_monitor_FBTC_GW_IBCM2(&_message->mon1, FBTC_GW_IBCM2_CANID);

AfterParse_CCAN_FBTC_GW_IBCM2(void);
	return FBTC_GW_IBCM2_CANID;
}

uint32_t Pack_CCAN_FBTC_GW_IBCM2(CCAN_FBTC_GW_IBCM2_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->BCM_HighBeamStatus << 7;
	_data[0] |= _message->BCM_HazardLampSt << 6;
	_data[0] |= _message->BCM_PositionLampSt << 5;
	_data[0] |= _message->BCM_RightligthFaultSt << 4;
	_data[0] |= _message->BCM_RightligthSt << 3;
	_data[0] |= _message->BCM_LetfligthFaultSt << 2;
	_data[0] |= _message->BCM_LetfligthSt << 1;
	_data[0] |= _message->BCM_TrunkSt;
	_data[1] |= _message->BCM_FuleTap_LockStatus << 7;
	_data[1] |= _message->BCM_LRDoorSwitchSt << 6;
	_data[1] |= _message->BCM_RRDoorSwitchSt << 5;
	_data[1] |= _message->BCM_RFDoorSwitchSt << 4;
	_data[1] |= _message->BCM_LFDoorSwitchSt << 3;
	_data[1] |= _message->BCM_frontFogligthSt << 2;
	_data[1] |= _message->BCM_BackFogligthSt << 1;
	_data[1] |= _message->BCM_LowBeamStatus;
	_data[2] |= _message->BCM_RightTurnSwitchrSt << 6;
	_data[2] |= _message->BCM_LeftTurnSwitchSt << 4;
	_data[2] |= _message->BCM_Lock_LED_Output << 3;
	_data[2] |= _message->BCM_AutoLockFunctionSt << 2;
	_data[2] |= _message->BCM_RearWindowHeatSt << 1;
	_data[3] |= _message->BCM_FRTurnlightFbSt << 7;
	_data[3] |= _message->BCM_RRTurnlightFbSt << 6;
	_data[3] |= _message->BCM_FLTurnlightFbSt << 5;
	_data[3] |= _message->BCM_RLTurnlightFbSt << 4;
	_data[3] |= _message->BCM_LampWashSt << 3;
	_data[3] |= _message->BCM_EngHoodUnlockWarming << 2;
	_data[3] |= _message->BCM_ReverseLampSwitchSt;
	_data[4] |= _message->BCM_RecentlyLockType << 4;
	_data[4] |= _message->BCM_RecentlyUnlockType;
	_data[5] |= _message->BCM_RLS_AUTO_SwitchSt << 6;
	_data[5] |= _message->BCM_FollowMeHomeSt << 2;
	_data[5] |= _message->BCM_FrontWiperWorkSt;
	_data[6] |= _message->BCM_MirrorFoldSwitchSt << 6;
	_data[6] |= _message->BCM_SunShadeStatus << 5;
	_data[6] |= _message->BCM_RoofWindowStatus << 4;
	_data[6] |= _message->BCM_RRWindowStatus << 3;
	_data[6] |= _message->BCM_RFWindowStatus << 2;
	_data[6] |= _message->BCM_RLWindowStatus << 1;
	_data[6] |= _message->BCM_LFWindowStatus;
	_data[7] |= _message->BCM_TailgateUnlockInform << 7;
	_data[7] |= _message->BCM_TailgateOpenSwitch << 6;
	_data[7] |= _message->BCM_FrontWiper_AUTO << 4;
	_data[7] |= _message->BCM_LowBeam_AUTO << 2;

	*_dlc = FBTC_GW_IBCM2_DLC;
	*_ide = FBTC_GW_IBCM2_IDE;
	return FBTC_GW_IBCM2_CANID;
}

/*
Message Name: FCTB_ACU_Crash
Message Id: 0x30c (780)
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|        Signal Name         | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|     RollingCounter30C      |     4     |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|     ACU_AirbagLampSts      |     2     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|        ACU_Crashout        |     0     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| ACU_PassengerBeltSwitchSig |     9     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  ACU_DriverBeltSwitchSig   |     8     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     ACU_CrashoutValid      |     18    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      ACU_CheckSum_ACU      |     56    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ACU_Crash(CCAN_FCTB_ACU_Crash_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ACU_Crash(void);
	_message->RollingCounter30C = (_data[0] & 0xF0U) >> 4;
	_message->ACU_AirbagLampSts = (_data[0] & 0x0CU) >> 2;
	_message->ACU_Crashout = _data[0] & 0x03U;
	_message->ACU_PassengerBeltSwitchSig = (_data[1] & 0x02U) >> 1;
	_message->ACU_DriverBeltSwitchSig = _data[1] & 0x01U;
	_message->ACU_CrashoutValid = (_data[2] & 0x04U) >> 2;
	_message->ACU_CheckSum_ACU = _data[7] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ACU_Crash_DLC);
	CCAN_monitor_FCTB_ACU_Crash(&_message->mon1, FCTB_ACU_Crash_CANID);

AfterParse_CCAN_FCTB_ACU_Crash(void);
	return FCTB_ACU_Crash_CANID;
}

uint32_t Pack_CCAN_FCTB_ACU_Crash(CCAN_FCTB_ACU_Crash_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->RollingCounter30C << 4;
	_data[0] |= _message->ACU_AirbagLampSts << 2;
	_data[0] |= _message->ACU_Crashout;
	_data[1] |= _message->ACU_PassengerBeltSwitchSig << 1;
	_data[1] |= _message->ACU_DriverBeltSwitchSig;
	_data[2] |= _message->ACU_CrashoutValid << 2;
	_data[7] |= _message->ACU_CheckSum_ACU;

	*_dlc = FCTB_ACU_Crash_DLC;
	*_ide = FCTB_ACU_Crash_IDE;
	return FCTB_ACU_Crash_CANID;
}

/*
Message Name: FCTB_TAS_SAS_Info
Message Id: 0xa5 (165)
+-----------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|      Signal Name      | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+-----------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| TAS_SAS_SteeringAngle |     8     |   16   | big_endian |        True        |   1    |   0    | None |   None   |
+-----------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_TAS_SAS_Info(CCAN_FCTB_TAS_SAS_Info_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_TAS_SAS_Info(void);
	_message->TAS_SAS_SteeringAngle = (_data[0] & 0xFFU) << 8 | (_data[1] & 0xFFU);

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_TAS_SAS_Info_DLC);
	CCAN_monitor_FCTB_TAS_SAS_Info(&_message->mon1, FCTB_TAS_SAS_Info_CANID);

AfterParse_CCAN_FCTB_TAS_SAS_Info(void);
	return FCTB_TAS_SAS_Info_CANID;
}

uint32_t Pack_CCAN_FCTB_TAS_SAS_Info(CCAN_FCTB_TAS_SAS_Info_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= (_message->TAS_SAS_SteeringAngle >> 8) & 0xFFU;
	_data[1] |= _message->TAS_SAS_SteeringAngle & 0xFFU;

	*_dlc = FCTB_TAS_SAS_Info_DLC;
	*_ide = FCTB_TAS_SAS_Info_IDE;
	return FCTB_TAS_SAS_Info_CANID;
}

/*
Message Name: FCTB_ESC_FPB1
Message Id: 0x31a (794)
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|          Signal Name          | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|    ESC_EPBDisplayMessageReq   |     5     |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_EPBCruiseControlCancel  |     4     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_EPBWarningIndicationReq  |     2     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_EPBSwitchStatics     |     12    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_EPBSwitchStaticsValidity |     11    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|         ESC_EPBStatus         |     8     |   3    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_CurrentOnRightRearCaliper |     30    |   10   | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_CurrentOnLeftRearCaliper |     36    |   10   | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_PbcActuatorStateRight   |     45    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_PbcActuatorStateLeft   |     42    |   3    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_RollingCount_EPB     |     48    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|        ESC_CheckSum_EPB       |     56    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+-------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ESC_FPB1(CCAN_FCTB_ESC_FPB1_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ESC_FPB1(void);
	_message->ESC_EPBDisplayMessageReq = (_data[0] & 0xE0U) >> 5;
	_message->ESC_EPBCruiseControlCancel = (_data[0] & 0x10U) >> 4;
	_message->ESC_EPBWarningIndicationReq = (_data[0] & 0x0CU) >> 2;
	_message->ESC_EPBSwitchStatics = (_data[1] & 0x30U) >> 4;
	_message->ESC_EPBSwitchStaticsValidity = (_data[1] & 0x08U) >> 3;
	_message->ESC_EPBStatus = _data[1] & 0x07U;
	_message->ESC_CurrentOnRightRearCaliper = (_data[2] & 0xFFU) << 2 | (_data[3] & 0xC0U) >> 6;
	_message->ESC_CurrentOnLeftRearCaliper = (_data[3] & 0x3FU) << 4 | (_data[4] & 0xF0U) >> 4;
	_message->ESC_PbcActuatorStateRight = (_data[5] & 0xE0U) >> 5;
	_message->ESC_PbcActuatorStateLeft = (_data[5] & 0x1CU) >> 2;
	_message->ESC_RollingCount_EPB = _data[6] & 0x0FU;
	_message->ESC_CheckSum_EPB = _data[7] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ESC_FPB1_DLC);
	CCAN_monitor_FCTB_ESC_FPB1(&_message->mon1, FCTB_ESC_FPB1_CANID);

AfterParse_CCAN_FCTB_ESC_FPB1(void);
	return FCTB_ESC_FPB1_CANID;
}

uint32_t Pack_CCAN_FCTB_ESC_FPB1(CCAN_FCTB_ESC_FPB1_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->ESC_EPBDisplayMessageReq << 5;
	_data[0] |= _message->ESC_EPBCruiseControlCancel << 4;
	_data[0] |= _message->ESC_EPBWarningIndicationReq << 2;
	_data[1] |= _message->ESC_EPBSwitchStatics << 4;
	_data[1] |= _message->ESC_EPBSwitchStaticsValidity << 3;
	_data[1] |= _message->ESC_EPBStatus;
	_data[2] |= (_message->ESC_CurrentOnRightRearCaliper >> 2) & 0xFFU;
	_data[3] |= (_message->ESC_CurrentOnRightRearCaliper << 2) & 0xC0U;
	_data[3] |= (_message->ESC_CurrentOnLeftRearCaliper >> 4) & 0x3FU;
	_data[4] |= (_message->ESC_CurrentOnLeftRearCaliper << 4) & 0xF0U;
	_data[5] |= _message->ESC_PbcActuatorStateRight << 5;
	_data[5] |= _message->ESC_PbcActuatorStateLeft << 2;
	_data[6] |= _message->ESC_RollingCount_EPB;
	_data[7] |= _message->ESC_CheckSum_EPB;

	*_dlc = FCTB_ESC_FPB1_DLC;
	*_ide = FCTB_ESC_FPB1_IDE;
	return FCTB_ESC_FPB1_CANID;
}

/*
Message Name: FCTB_ESC7
Message Id: 0x431 (1073)
+----------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|           Signal Name            | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+----------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| ESC_ITPMSFrontRightPressureWarn  |     6     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_ITPMSFrontLeftPressureWarn  |     4     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_ITPMSRearRightPressureWarnin |     2     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_ITPMSRearLeftPressureWarning |     0     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_DDSSystemStatus        |     12    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_ITPMSWarningStatus      |     9     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_ITPMSMalfunctionStatus    |     8     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
+----------------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ESC7(CCAN_FCTB_ESC7_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ESC7(void);
	_message->ESC_ITPMSFrontRightPressureWarn = (_data[0] & 0xC0U) >> 6;
	_message->ESC_ITPMSFrontLeftPressureWarn = (_data[0] & 0x30U) >> 4;
	_message->ESC_ITPMSRearRightPressureWarnin = (_data[0] & 0x0CU) >> 2;
	_message->ESC_ITPMSRearLeftPressureWarning = _data[0] & 0x03U;
	_message->ESC_DDSSystemStatus = (_data[1] & 0xF0U) >> 4;
	_message->ESC_ITPMSWarningStatus = (_data[1] & 0x02U) >> 1;
	_message->ESC_ITPMSMalfunctionStatus = _data[1] & 0x01U;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ESC7_DLC);
	CCAN_monitor_FCTB_ESC7(&_message->mon1, FCTB_ESC7_CANID);

AfterParse_CCAN_FCTB_ESC7(void);
	return FCTB_ESC7_CANID;
}

uint32_t Pack_CCAN_FCTB_ESC7(CCAN_FCTB_ESC7_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->ESC_ITPMSFrontRightPressureWarn << 6;
	_data[0] |= _message->ESC_ITPMSFrontLeftPressureWarn << 4;
	_data[0] |= _message->ESC_ITPMSRearRightPressureWarnin << 2;
	_data[0] |= _message->ESC_ITPMSRearLeftPressureWarning;
	_data[1] |= _message->ESC_DDSSystemStatus << 4;
	_data[1] |= _message->ESC_ITPMSWarningStatus << 1;
	_data[1] |= _message->ESC_ITPMSMalfunctionStatus;

	*_dlc = FCTB_ESC7_DLC;
	*_ide = FCTB_ESC7_IDE;
	return FCTB_ESC7_CANID;
}

/*
Message Name: FCTB_ESC6
Message Id: 0x123 (291)
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|        Signal Name         | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|  ESC_DynamicSlopeAccuracy  |     6     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_AVHFunctionSwitch    |     5     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_AVHAvailable      |     3     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_AVH_Status       |     2     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_AVH_DisplayMessageReq  |     1     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_BLRequest        |     0     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_EmergencyBrakeLightReq |     15    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     ESC_BrakingEffort      |     14    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_MSRinRegulation     |     13    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_BrakeReleasedFailsafe  |     12    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_UnfilteredYawRate    |     16    |   12   | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_VehDrivingDirection   |     30    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_DynamicSlope      |     24    |   6    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_VehicleHoldStatus    |     36    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_HBAStatus        |     46    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_cdpAvailable      |     43    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_cdpActive        |     42    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_RollingCount_ESC6    |     48    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|     ESC_CheckSum_ESC6      |     56    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ESC6(CCAN_FCTB_ESC6_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ESC6(void);
	_message->ESC_DynamicSlopeAccuracy = (_data[0] & 0xC0U) >> 6;
	_message->ESC_AVHFunctionSwitch = (_data[0] & 0x20U) >> 5;
	_message->ESC_AVHAvailable = (_data[0] & 0x08U) >> 3;
	_message->ESC_AVH_Status = (_data[0] & 0x04U) >> 2;
	_message->ESC_AVH_DisplayMessageReq = (_data[0] & 0x02U) >> 1;
	_message->ESC_BLRequest = _data[0] & 0x01U;
	_message->ESC_EmergencyBrakeLightReq = (_data[1] & 0x80U) >> 7;
	_message->ESC_BrakingEffort = (_data[1] & 0x40U) >> 6;
	_message->ESC_MSRinRegulation = (_data[1] & 0x20U) >> 5;
	_message->ESC_BrakeReleasedFailsafe = (_data[1] & 0x10U) >> 4;
	_message->ESC_UnfilteredYawRate = (_data[1] & 0x0FU) << 8 | (_data[2] & 0xFFU);
	_message->ESC_VehDrivingDirection = (_data[3] & 0xC0U) >> 6;
	_message->ESC_DynamicSlope = _data[3] & 0x3FU;
	_message->ESC_VehicleHoldStatus = (_data[4] & 0x30U) >> 4;
	_message->ESC_HBAStatus = (_data[5] & 0xC0U) >> 6;
	_message->ESC_cdpAvailable = (_data[5] & 0x08U) >> 3;
	_message->ESC_cdpActive = (_data[5] & 0x04U) >> 2;
	_message->ESC_RollingCount_ESC6 = _data[6] & 0x0FU;
	_message->ESC_CheckSum_ESC6 = _data[7] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ESC6_DLC);
	CCAN_monitor_FCTB_ESC6(&_message->mon1, FCTB_ESC6_CANID);

AfterParse_CCAN_FCTB_ESC6(void);
	return FCTB_ESC6_CANID;
}

uint32_t Pack_CCAN_FCTB_ESC6(CCAN_FCTB_ESC6_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->ESC_DynamicSlopeAccuracy << 6;
	_data[0] |= _message->ESC_AVHFunctionSwitch << 5;
	_data[0] |= _message->ESC_AVHAvailable << 3;
	_data[0] |= _message->ESC_AVH_Status << 2;
	_data[0] |= _message->ESC_AVH_DisplayMessageReq << 1;
	_data[0] |= _message->ESC_BLRequest;
	_data[1] |= _message->ESC_EmergencyBrakeLightReq << 7;
	_data[1] |= _message->ESC_BrakingEffort << 6;
	_data[1] |= _message->ESC_MSRinRegulation << 5;
	_data[1] |= _message->ESC_BrakeReleasedFailsafe << 4;
	_data[1] |= (_message->ESC_UnfilteredYawRate >> 8) & 0x0FU;
	_data[2] |= _message->ESC_UnfilteredYawRate & 0xFFU;
	_data[3] |= _message->ESC_VehDrivingDirection << 6;
	_data[3] |= _message->ESC_DynamicSlope;
	_data[4] |= _message->ESC_VehicleHoldStatus << 4;
	_data[5] |= _message->ESC_HBAStatus << 6;
	_data[5] |= _message->ESC_cdpAvailable << 3;
	_data[5] |= _message->ESC_cdpActive << 2;
	_data[6] |= _message->ESC_RollingCount_ESC6;
	_data[7] |= _message->ESC_CheckSum_ESC6;

	*_dlc = FCTB_ESC6_DLC;
	*_ide = FCTB_ESC6_IDE;
	return FCTB_ESC6_CANID;
}

/*
Message Name: FCTB_ESC3
Message Id: 0x121 (289)
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|        Signal Name         | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
| ESC_ReqDecreaseTorqueFlag  |     7     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_ReqIncreaseTorqueFlag  |     6     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_TCSCtlActive      |     4     |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_ESCAlarmSig       |     3     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     ESC_ESCWorkStatus      |     2     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_keepingGear       |     1     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|         ESC_ESCOFF         |     0     |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_ReqIncreaseTorque    |     20    |   12   | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_ReqDecreaseTorque    |     24    |   12   | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_epbRequest       |     38    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_wheelDirectionRLValid  |     37    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_wheelDirectionRRValid  |     36    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_FRWDirection      |     34    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_FLWDirection      |     32    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_RRWDirection      |     46    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_RLWDirection      |     44    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|      ESC_ESCValidity       |     43    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_vehicleStandstillValid |     42    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     ESC_TCSErrorStatus     |     41    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_VehicleStandstill    |     52    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|  GW_ESC_RollingCount_ESC3  |     48    |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|    GW_ESC_CheckSum_ESC3    |     56    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
+----------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ESC3(CCAN_FCTB_ESC3_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ESC3(void);
	_message->ESC_ReqDecreaseTorqueFlag = (_data[0] & 0x80U) >> 7;
	_message->ESC_ReqIncreaseTorqueFlag = (_data[0] & 0x40U) >> 6;
	_message->ESC_TCSCtlActive = (_data[0] & 0x30U) >> 4;
	_message->ESC_ESCAlarmSig = (_data[0] & 0x08U) >> 3;
	_message->ESC_ESCWorkStatus = (_data[0] & 0x04U) >> 2;
	_message->ESC_keepingGear = (_data[0] & 0x02U) >> 1;
	_message->ESC_ESCOFF = _data[0] & 0x01U;
	_message->ESC_ReqIncreaseTorque = (_data[1] & 0xFFU) << 4 | (_data[2] & 0xF0U) >> 4;
	_message->ESC_ReqDecreaseTorque = (_data[2] & 0x0FU) << 8 | (_data[3] & 0xFFU);
	_message->ESC_epbRequest = (_data[4] & 0xC0U) >> 6;
	_message->ESC_wheelDirectionRLValid = (_data[4] & 0x20U) >> 5;
	_message->ESC_wheelDirectionRRValid = (_data[4] & 0x10U) >> 4;
	_message->ESC_FRWDirection = (_data[4] & 0x0CU) >> 2;
	_message->ESC_FLWDirection = _data[4] & 0x03U;
	_message->ESC_RRWDirection = (_data[5] & 0xC0U) >> 6;
	_message->ESC_RLWDirection = (_data[5] & 0x30U) >> 4;
	_message->ESC_ESCValidity = (_data[5] & 0x08U) >> 3;
	_message->ESC_vehicleStandstillValid = (_data[5] & 0x04U) >> 2;
	_message->ESC_TCSErrorStatus = (_data[5] & 0x02U) >> 1;
	_message->ESC_VehicleStandstill = (_data[6] & 0x30U) >> 4;
	_message->GW_ESC_RollingCount_ESC3 = _data[6] & 0x0FU;
	_message->GW_ESC_CheckSum_ESC3 = _data[7] & 0xFFU;

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ESC3_DLC);
	CCAN_monitor_FCTB_ESC3(&_message->mon1, FCTB_ESC3_CANID);

AfterParse_CCAN_FCTB_ESC3(void);
	return FCTB_ESC3_CANID;
}

uint32_t Pack_CCAN_FCTB_ESC3(CCAN_FCTB_ESC3_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= _message->ESC_ReqDecreaseTorqueFlag << 7;
	_data[0] |= _message->ESC_ReqIncreaseTorqueFlag << 6;
	_data[0] |= _message->ESC_TCSCtlActive << 4;
	_data[0] |= _message->ESC_ESCAlarmSig << 3;
	_data[0] |= _message->ESC_ESCWorkStatus << 2;
	_data[0] |= _message->ESC_keepingGear << 1;
	_data[0] |= _message->ESC_ESCOFF;
	_data[1] |= (_message->ESC_ReqIncreaseTorque >> 4) & 0xFFU;
	_data[2] |= (_message->ESC_ReqIncreaseTorque << 4) & 0xF0U;
	_data[2] |= (_message->ESC_ReqDecreaseTorque >> 8) & 0x0FU;
	_data[3] |= _message->ESC_ReqDecreaseTorque & 0xFFU;
	_data[4] |= _message->ESC_epbRequest << 6;
	_data[4] |= _message->ESC_wheelDirectionRLValid << 5;
	_data[4] |= _message->ESC_wheelDirectionRRValid << 4;
	_data[4] |= _message->ESC_FRWDirection << 2;
	_data[4] |= _message->ESC_FLWDirection;
	_data[5] |= _message->ESC_RRWDirection << 6;
	_data[5] |= _message->ESC_RLWDirection << 4;
	_data[5] |= _message->ESC_ESCValidity << 3;
	_data[5] |= _message->ESC_vehicleStandstillValid << 2;
	_data[5] |= _message->ESC_TCSErrorStatus << 1;
	_data[6] |= _message->ESC_VehicleStandstill << 4;
	_data[6] |= _message->GW_ESC_RollingCount_ESC3;
	_data[7] |= _message->GW_ESC_CheckSum_ESC3;

	*_dlc = FCTB_ESC3_DLC;
	*_ide = FCTB_ESC3_IDE;
	return FCTB_ESC3_CANID;
}

/*
Message Name: FCTB_ESC2
Message Id: 0xa0 (160)
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|      Signal Name       | Start Bit | Length | Byte Order | Value Type(Signed) | Factor | Offset | Unit | comments |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
|   ESC_BrakeOilPress    |     13    |   11   | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_RollingCount_ESC2  |     8     |   4    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_ABSWorkLable    |     19    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_ABSAlarmSig     |     28    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_ABSValidity     |     26    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|  ESC_VehSpdValidFlag   |     25    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|    ESC_EBDAlarmSig     |     24    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
| ESC_HBB_StatusValidity |     39    |   1    | big_endian |       False        |   1    |   0    | None |   None   |
|     ESC_HBB_Status     |     37    |   2    | big_endian |       False        |   1    |   0    | None |   None   |
|   ESC_CheckSum_ESC2    |     40    |   8    | big_endian |       False        |   1    |   0    | None |   None   |
|       ESC_VehSpd       |     56    |   16   | big_endian |       False        |   1    |   0    | None |   None   |
+------------------------+-----------+--------+------------+--------------------+--------+--------+------+----------+
*/
uint32_t Unpack_CCAN_FCTB_ESC2(CCAN_FCTB_ESC2_t* _message, const uint8_t _data[], uint8_t _dlc)
{
	BeforeParse_CCAN_FCTB_ESC2(void);
	_message->ESC_BrakeOilPress = (_data[0] & 0xFFU) << 3 | (_data[1] & 0xE0U) >> 5;
	_message->ESC_RollingCount_ESC2 = _data[1] & 0x0FU;
	_message->ESC_ABSWorkLable = (_data[2] & 0x08U) >> 3;
	_message->ESC_ABSAlarmSig = (_data[3] & 0x10U) >> 4;
	_message->ESC_ABSValidity = (_data[3] & 0x04U) >> 2;
	_message->ESC_VehSpdValidFlag = (_data[3] & 0x02U) >> 1;
	_message->ESC_EBDAlarmSig = _data[3] & 0x01U;
	_message->ESC_HBB_StatusValidity = (_data[4] & 0x80U) >> 7;
	_message->ESC_HBB_Status = (_data[4] & 0x60U) >> 5;
	_message->ESC_CheckSum_ESC2 = _data[5] & 0xFFU;
	_message->ESC_VehSpd = (_data[6] & 0xFFU) << 8 | (_data[7] & 0xFFU);

	_message->mon1.last_cycle = CCAN_GetSystemTick();
	_message->mon1.timeout_cnt = 0;
	_message->mon1.frame_cnt++;
	_message->mon1.dlc_error = (_dlc != FCTB_ESC2_DLC);
	CCAN_monitor_FCTB_ESC2(&_message->mon1, FCTB_ESC2_CANID);

AfterParse_CCAN_FCTB_ESC2(void);
	return FCTB_ESC2_CANID;
}

uint32_t Pack_CCAN_FCTB_ESC2(CCAN_FCTB_ESC2_t* _message, uint8_t* _data, uint8_t* _dlc, uint8_t* _ide)
{
	(void)memset(_data, 0, sizeof(_data));

	_data[0] |= (_message->ESC_BrakeOilPress >> 3) & 0xFFU;
	_data[1] |= (_message->ESC_BrakeOilPress << 3) & 0xE0U;
	_data[1] |= _message->ESC_RollingCount_ESC2;
	_data[2] |= _message->ESC_ABSWorkLable << 3;
	_data[3] |= _message->ESC_ABSAlarmSig << 4;
	_data[3] |= _message->ESC_ABSValidity << 2;
	_data[3] |= _message->ESC_VehSpdValidFlag << 1;
	_data[3] |= _message->ESC_EBDAlarmSig;
	_data[4] |= _message->ESC_HBB_StatusValidity << 7;
	_data[4] |= _message->ESC_HBB_Status << 5;
	_data[5] |= _message->ESC_CheckSum_ESC2;
	_data[6] |= (_message->ESC_VehSpd >> 8) & 0xFFU;
	_data[7] |= _message->ESC_VehSpd & 0xFFU;

	*_dlc = FCTB_ESC2_DLC;
	*_ide = FCTB_ESC2_IDE;
	return FCTB_ESC2_CANID;
}



/******** END OF FILE ********/
